# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: my-name@my-org.org
full_name: My Name
gh_action_docs_preview: false
gh_action_pypi: true
github_org: monarch-initiative
license: BSD-3-Clause
project_description: This is the project description.
project_name: dismech
project_slug: dismech

