# Custom reference sources for dismech
# See: https://linkml.github.io/linkml-reference-validator/how-to/add-reference-source/

sources:
  MGNIFY:
    url_template: "https://www.ebi.ac.uk/metagenomics/api/v1/studies/{id}"
    id_patterns:
      - "^MGYS\\d+$"
    fields:
      title: "$.data.attributes.study-name"
      content: "$.data.attributes.study-abstract"
    headers:
      Accept: "application/json"
