# Configuration for linkml-reference-validator
# See: https://github.com/linkml/linkml-reference-validator

cache_dir: references_cache

# Skip validation for unsupported reference types
# These will return is_valid=True with INFO severity
skip_prefixes:
  - SRA
  - BIOPROJECT

# For any other unfetchable references, treat as warning instead of error
unknown_prefix_severity: WARNING
