"""Contract tests for the committed grouping closure cache (``cache/closure/``).

``cache/closure/<prefix>.csv`` holds the is_a/part_of closure of every HP/GO
term a grouping's membership criteria are evaluated over, so the audit runs
offline and deterministically. Like the term caches it is derived, sorted, and
regenerated by tooling (``just build-grouping-closure-cache``), never hand
edited. Two things are checked:

* the files follow the structural contract (cheap; always runs);
* every criterion term across ``kb/groupings/`` has a cached closure
  (``kb_data``), because a term with no closure evaluates to UNKNOWN and an
  UNKNOWN leaf makes a NECESSARY criterion unauditable for that member.
"""

from __future__ import annotations

import csv
import glob
from pathlib import Path

import pytest

from dismech import groupings as G
from dismech.yaml_io import safe_load

CACHE_FILES = sorted(G.CLOSURE_CACHE_DIR.glob("*.csv"))
GROUPING_FILES = sorted(glob.glob(str(G.GROUPINGS_DIR / "*.yaml")))


def test_a_closure_cache_exists_for_every_closure_prefix():
    missing = [
        p for p in sorted(G.CLOSURE_PREFIXES) if not G.closure_cache_path(p).is_file()
    ]
    assert not missing, (
        f"No closure cache for {missing}; run `just build-grouping-closure-cache`"
    )


@pytest.mark.parametrize("path", CACHE_FILES, ids=lambda p: p.name)
def test_closure_cache_follows_the_structural_contract(path: Path):
    prefix = path.stem.upper()
    assert prefix in G.CLOSURE_PREFIXES, f"{path.name}: not a closure prefix"

    with open(path, newline="") as f:
        rows = list(csv.reader(f))
    assert tuple(rows[0]) == G.CLOSURE_CACHE_HEADER, f"{path.name}: bad header"
    body = rows[1:]

    problems = []
    if body != sorted(body):
        problems.append("rows are not sorted")
    if len(body) != len(set(map(tuple, body))):
        problems.append("duplicate rows")
    terms = {term for term, _ in body}
    for term, descendant in body:
        if not term.startswith(f"{prefix}:") or not descendant.startswith(f"{prefix}:"):
            problems.append(f"{term},{descendant}: wrong prefix for {path.name}")
    for term in sorted(terms):
        if (term, term) not in map(tuple, body):
            problems.append(f"{term}: missing reflexive row")
    assert not problems, f"{path.name}: {problems}"


@pytest.mark.kb_data
@pytest.mark.parametrize("filepath", GROUPING_FILES, ids=lambda p: Path(p).name)
def test_every_criterion_term_has_a_cached_closure(filepath: str):
    with open(filepath) as f:
        grouping = safe_load(f)
    missing = G.uncached_closure_terms(grouping)
    assert not missing, (
        f"{Path(filepath).name}: no cached closure for {missing}; run "
        "`just build-grouping-closure-cache` and commit cache/closure/"
    )
