from pathlib import Path

from dismech.qc_dashboard import (
    CAPABILITY_BLOCK_END,
    CAPABILITY_BLOCK_START,
    UNCURATED_BLOCK_END,
    UNCURATED_BLOCK_START,
    collect_capability_metrics,
    collect_uncurated_disease_references,
    generate_capability_metrics_report,
    generate_uncurated_dashboard_report,
)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def test_collect_uncurated_references_excludes_subtype_grounding(
    tmp_path: Path,
) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    _write(
        kb_dir / "Acne_Vulgaris.yaml",
        """
name: Acne Vulgaris
disease_term:
  preferred_term: acne vulgaris
  term:
    id: MONDO:1000001
    label: acne vulgaris
differential_diagnoses:
  - name: Rosacea-like Dermatitis
    disease_term:
      preferred_term: Rosacea-like Dermatitis
      term:
        id: MONDO:1000999
        label: rosacea-like dermatitis
""",
    )
    _write(
        kb_dir / "Rosacea.yaml",
        """
name: Rosacea
disease_term:
  term:
    id: MONDO:1000002
    label: rosacea
""",
    )
    _write(
        kb_dir / "Psoriasis.yaml",
        """
name: Psoriasis
disease_term:
  term:
    id: MONDO:1000003
    label: psoriasis
has_subtypes:
  - name: Dermatitis overlap subtype
    subtype_term:
      preferred_term: Rosacea-like Dermatitis
      term:
        id: MONDO:1000999
        label: rosacea-like dermatitis
""",
    )

    rows = collect_uncurated_disease_references(kb_dir)

    assert len(rows) == 1
    row = rows[0]
    assert row["disease_name"] == "Rosacea-like Dermatitis"
    assert row["mondo_id"] == "MONDO:1000999"
    assert row["linking_pages_count"] == 1
    assert [page["name"] for page in row["linking_pages"]] == ["Acne Vulgaris"]


def test_generate_report_ignores_subtype_grounding(tmp_path: Path) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    dashboard_index = dashboard_dir / "index.html"

    _write(
        kb_dir / "Disease_A.yaml",
        """
name: Disease A
disease_term:
  term:
    id: MONDO:2000001
    label: disease a
has_subtypes:
  - name: Missing Disease
    subtype_term:
      term:
        id: MONDO:2000999
        label: missing disease
""",
    )
    _write(
        kb_dir / "Disease_B.yaml",
        """
name: Disease B
disease_term:
  term:
    id: MONDO:2000002
    label: disease b
""",
    )
    _write(
        dashboard_index,
        """
<!DOCTYPE html>
<html>
<body>
  <section class="chart-card">
    <h2>Existing Section</h2>
  </section>
  <footer>Generated by linkml-data-qc</footer>
</body>
</html>
""",
    )

    result_1 = generate_uncurated_dashboard_report(
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        dashboard_index_path=dashboard_index,
    )
    result_2 = generate_uncurated_dashboard_report(
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        dashboard_index_path=dashboard_index,
    )

    assert result_1["summary"]["total_uncurated_disease_terms"] == 0
    assert result_1["summary"]["total_linking_pages"] == 0
    assert (dashboard_dir / "not_yet_curated.html").exists()
    assert (dashboard_dir / "not_yet_curated.json").exists()

    index_content = dashboard_index.read_text(encoding="utf-8")
    assert "not_yet_curated.html" in index_content
    assert index_content.count(UNCURATED_BLOCK_START) == 1
    assert index_content.count(UNCURATED_BLOCK_END) == 1

    # Second pass should detect existing block and keep a single injected section.
    assert result_2["summary"]["total_uncurated_disease_terms"] == 0
    assert dashboard_index.read_text(encoding="utf-8").count(UNCURATED_BLOCK_START) == 1


def test_duplicate_curated_mondo_id_is_not_reported_as_uncurated(
    tmp_path: Path,
) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    _write(
        kb_dir / "Variant_A.yaml",
        """
name: Variant A
disease_term:
  term:
    id: MONDO:3000001
    label: duplicate disease
""",
    )
    _write(
        kb_dir / "Variant_B.yaml",
        """
name: Variant B
disease_term:
  term:
    id: MONDO:3000001
    label: duplicate disease
""",
    )
    _write(
        kb_dir / "Source.yaml",
        """
name: Source
disease_term:
  term:
    id: MONDO:3000002
    label: source disease
differential_diagnoses:
  - name: Duplicate disease
    disease_term:
      term:
        id: MONDO:3000001
        label: duplicate disease
""",
    )

    rows = collect_uncurated_disease_references(kb_dir)
    assert rows == []


def test_collect_capability_metrics_aggregates_public_qc_stats(tmp_path: Path) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    reports_path = tmp_path / "dashboard" / "reports.json"
    _write(
        kb_dir / "Disease_A.yaml",
        """
name: Disease A
category: Genetic
creation_date: "2026-01-15T00:00:00Z"
updated_date: "2026-02-01T00:00:00Z"
disease_term:
  term:
    id: MONDO:4000001
    label: disease a
phenotypes:
  - name: Muscle weakness
    phenotype_term:
      term:
        id: HP:0001324
        label: Muscle weakness
pathophysiology:
  - name: Driver event
    conforms_to: "example_module#Driver event"
    cell_types:
      - term:
          id: CL:0000187
          label: muscle cell
    biological_processes:
      - term:
          id: GO:0006936
          label: muscle contraction
    evidence:
      - reference: PMID:1
        supports: SUPPORT
        evidence_source: HUMAN_CLINICAL
        snippet: exact quote
    downstream:
      - target: Downstream event
treatments:
  - name: Physical Therapy
    evidence:
      - reference: PMID:2
        supports: SUPPORT
        evidence_source: HUMAN_CLINICAL
        snippet: exact quote
clinical_trials:
  - name: NCT00000001
    evidence:
      - reference: clinicaltrials:NCT00000001
        supports: SUPPORT
        evidence_source: HUMAN_CLINICAL
        snippet: exact quote
""",
    )
    _write(
        kb_dir / "Disease_B.yaml",
        """
name: Disease B
category: Immune
creation_date: "2026-02-15T00:00:00Z"
updated_date: "2026-02-20T00:00:00Z"
disease_term:
  term:
    id: MONDO:4000002
    label: disease b
pathophysiology:
  - name: Immune event
    evidence:
      - reference: PMID:3
        supports: SUPPORT
        evidence_source: IN_VITRO
        snippet: exact quote
""",
    )
    _write(
        reports_path,
        """
[
  {
    "file": "Disease_A.yaml",
    "global_compliance": 70.0,
    "weighted_compliance": 80.0,
    "violations": 1
  },
  {
    "file": "Disease_B.yaml",
    "global_compliance": 50.0,
    "weighted_compliance": 60.0,
    "violations": 0
  }
]
""",
    )

    metrics = collect_capability_metrics(kb_dir=kb_dir, reports_path=reports_path)

    assert metrics["summary"] == {
        "total_entries": 2,
        "entries_with_mondo_id": 2,
        "total_evidence_items": 4,
        "unique_evidence_references": 4,
        "entries_with_treatments": 1,
        "entries_with_clinical_trials": 1,
        "total_pathophysiology_nodes": 2,
        "total_causal_edges": 1,
        "total_ontology_terms": 5,
        "average_global_compliance": 60.0,
        "average_weighted_compliance": 70.0,
        "total_compliance_violations": 1,
    }
    assert metrics["evidence_quality"]["evidence_source_counts"] == {
        "HUMAN_CLINICAL": 3,
        "IN_VITRO": 1,
    }
    assert metrics["ontology_richness"]["term_prefix_counts"] == {
        "CL": 1,
        "GO": 1,
        "HP": 1,
        "MONDO": 2,
    }
    assert metrics["mechanistic_depth"]["entries_with_module_conformance_percent"] == 50.0
    assert metrics["treatment_coverage"]["entries_with_clinical_trials_percent"] == 50.0
    assert metrics["curation_velocity"]["created_by_month"] == {
        "2026-01": 1,
        "2026-02": 1,
    }


def test_generate_capability_metrics_report_injects_index_link(tmp_path: Path) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    dashboard_index = dashboard_dir / "index.html"

    _write(
        kb_dir / "Disease_A.yaml",
        """
name: Disease A
disease_term:
  term:
    id: MONDO:5000001
    label: disease a
""",
    )
    _write(
        dashboard_index,
        """
<!DOCTYPE html>
<html>
<body>
  <section class="chart-card">
    <h2>Existing Section</h2>
  </section>
  <footer>Generated by linkml-data-qc</footer>
</body>
</html>
""",
    )

    result_1 = generate_capability_metrics_report(
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        dashboard_index_path=dashboard_index,
    )
    result_2 = generate_capability_metrics_report(
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        dashboard_index_path=dashboard_index,
    )

    assert result_1["summary"]["total_entries"] == 1
    assert (dashboard_dir / "capability_metrics.html").exists()
    assert (dashboard_dir / "capability_metrics.json").exists()

    index_content = dashboard_index.read_text(encoding="utf-8")
    assert "capability_metrics.html" in index_content
    assert index_content.count(CAPABILITY_BLOCK_START) == 1
    assert index_content.count(CAPABILITY_BLOCK_END) == 1

    assert result_2["summary"]["total_entries"] == 1
    assert dashboard_index.read_text(encoding="utf-8").count(CAPABILITY_BLOCK_START) == 1
