import json
from pathlib import Path

import pytest
import yaml

from dismech.compare.mondo_export import candidates_meta_path
from dismech.priority_dashboard import (
    PRIORITY_BLOCK_END,
    PRIORITY_BLOCK_START,
    generate_priority_dashboard_report,
)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def _write_yaml(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def _write_json(path: Path, payload: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def test_generate_priority_dashboard_report_builds_pages_and_injects_link(
    tmp_path: Path,
) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    dashboard_index = dashboard_dir / "index.html"
    candidates = tmp_path / "candidates.json"
    config = tmp_path / "config.yaml"

    _write_yaml(
        kb_dir / "Noonan_Syndrome.yaml",
        {
            "name": "Noonan Syndrome",
            "disease_term": {
                "term": {"id": "MONDO:0018997", "label": "Noonan syndrome"}
            },
        },
    )
    _write_json(
        candidates,
        [
            {
                "mondo_id": "MONDO:0002442",
                "label": "long QT syndrome",
                "definition": "Inherited repolarization disorder.",
                "synonyms": ["LQTS", "long-qt syndrome"],
                "parents": ["cardiac channelopathy"],
                "xrefs": ["OMIM:192500", "Orphanet:101019"],
                "child_count": 16,
                "clingen_definitive_count": 3,
                "subset_match_count": 1,
                "orphanet_match_count": 1,
                "categories": ["Cardiac"],
            },
            {
                "mondo_id": "MONDO:0018997",
                "label": "Noonan syndrome",
                "definition": "RASopathy with congenital heart disease.",
                "synonyms": ["Noonan syndrome 1 spectrum"],
                "parents": ["RASopathy"],
                "xrefs": ["OMIM:163950", "Orphanet:648"],
                "child_count": 6,
                "clingen_definitive_count": 3,
                "clingen_strong_count": 1,
                "subset_match_count": 1,
                "orphanet_match_count": 1,
                "categories": ["Cardiac", "Developmental"],
            },
            {
                "mondo_id": "MONDO:0010342",
                "label": "autism, susceptibility to, X-linked 3",
                "definition": "MECP2-linked susceptibility signal.",
                "synonyms": ["AUTSX3"],
                "parents": ["neurodevelopmental disorder"],
                "xrefs": ["OMIM:300496"],
                "subset_match_count": 1,
                "categories": ["Neurodevelopmental"],
            },
        ],
    )
    _write(
        config,
        """
weights:
  missing_from_dismech: 35
  has_definition: 6
  synonym_count: 1.5
  xref_count: 0.5
  clingen_definitive_count: 12
  clingen_strong_count: 6
  subset_match_count: 5
  orphanet_match_count: 4
  broad_parent_bonus: 8
  subtype_series_penalty: -18
  grouping_term_penalty: -28
  over_specific_leaf_penalty: -10
  obsolete_penalty: -100
  already_curated_penalty: -80
caps:
  synonym_count: 5
  xref_count: 8
  clingen_definitive_count: 3
  clingen_strong_count: 3
  subset_match_count: 3
  orphanet_match_count: 3
thresholds:
  broad_parent_min_children: 4
  subtype_series_min_family_size: 2
  over_specific_leaf_min_words: 7
heuristics:
  grouping_term_patterns:
    - "\\\\bsusceptibility\\\\b"
    - "^obsolete\\\\b"
  subtype_series_patterns:
    - "^(?P<stem>.+?),\\\\s*[0-9]+[A-Za-z]?$"
    - "^(?P<stem>.+?)\\\\s+[0-9]+[A-Za-z]?$"
""",
    )
    _write(
        dashboard_index,
        """
<!DOCTYPE html>
<html>
<body>
  <section class="chart-card">
    <h2>Existing Section</h2>
  </section>
  <footer>Generated by linkml-data-qc</footer>
</body>
</html>
""",
    )

    result_1 = generate_priority_dashboard_report(
        candidates_path=candidates,
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        config_path=config,
        dashboard_index_path=dashboard_index,
    )
    result_2 = generate_priority_dashboard_report(
        candidates_path=candidates,
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        config_path=config,
        dashboard_index_path=dashboard_index,
    )

    assert result_1["summary"]["total_candidates"] == 3
    assert result_1["summary"]["already_curated"] == 1
    assert result_1["summary"]["already_curated_excluded_from_export"] == 0
    assert result_1["summary"]["remaining_candidates"] == 2
    assert result_1["summary"]["root_action_candidates"] == 1
    assert result_1["summary"]["coverage_percent"] == pytest.approx(33.3)
    assert (dashboard_dir / "priority.html").exists()
    assert (dashboard_dir / "priority.json").exists()

    payload = json.loads((dashboard_dir / "priority.json").read_text(encoding="utf-8"))
    assert payload["summary"]["top_remaining_label"] == "long QT syndrome"
    assert payload["action_breakdown"][0]["action"] == "CURATE_ROOT_WITH_SUBTYPES"
    assert payload["category_summary"][0]["category"] == "Cardiac"
    assert payload["category_summary"][0]["remaining_candidates"] == 1
    assert payload["scoring"]["weights"]["missing_from_dismech"] == 35
    assert payload["scoring"]["thresholds"]["broad_parent_min_children"] == 4
    assert payload["rows"][0]["recommended_action"] == "CURATE_ROOT_WITH_SUBTYPES"

    html_report = (dashboard_dir / "priority.html").read_text(encoding="utf-8")
    assert "Top Uncurated Diseases" in html_report
    assert "Explore the Ranking" in html_report
    assert "Selected Candidate" in html_report
    assert "priority-dashboard-data" in html_report
    assert "long QT syndrome" in html_report
    assert "Category View" in html_report

    index_content = dashboard_index.read_text(encoding="utf-8")
    assert "priority.html" in index_content
    assert index_content.count(PRIORITY_BLOCK_START) == 1
    assert index_content.count(PRIORITY_BLOCK_END) == 1

    assert result_2["summary"]["remaining_candidates"] == 2
    assert dashboard_index.read_text(encoding="utf-8").count(PRIORITY_BLOCK_START) == 1


def test_curated_rows_dropped_by_the_exporter_still_count_as_coverage(
    tmp_path: Path,
) -> None:
    """The real pipeline never ships an ALREADY_CURATED row (#7425).

    ``just gen-priority-dashboard`` runs the MONDO exporter with ``--kb-dir``,
    which drops every already-curated root before the TSV is written. Counting
    only the surviving curated rows therefore reported ``already_curated: 0``
    and ``coverage_percent: 0.0`` against a KB of well over a thousand
    disorders. The dropped count arrives in the export's sidecar and belongs in
    both halves of the fraction.
    """
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    candidates = tmp_path / "candidates.json"
    config = tmp_path / "config.yaml"

    _write_json(
        candidates,
        [
            {
                "mondo_id": "MONDO:0002442",
                "label": "long QT syndrome",
                "definition": "Inherited repolarization disorder.",
                "synonyms": ["LQTS"],
                "parents": ["cardiac channelopathy"],
                "xrefs": ["OMIM:192500"],
                "child_count": 16,
            },
            {
                "mondo_id": "MONDO:0010342",
                "label": "autism, susceptibility to, X-linked 3",
                "definition": "MECP2-linked susceptibility signal.",
                "synonyms": ["AUTSX3"],
                "parents": ["neurodevelopmental disorder"],
                "xrefs": ["OMIM:300496"],
            },
        ],
    )
    _write(
        candidates_meta_path(candidates),
        json.dumps(
            {
                "disease_root_id": "MONDO:0000001",
                "kb_dir": str(kb_dir),
                "total_descendants": 8,
                "excluded_curated": 6,
                "exported_rows": 2,
            }
        ),
    )
    _write(
        config,
        """
weights: {}
caps: {}
thresholds:
  broad_parent_min_children: 4
  subtype_series_min_family_size: 2
  over_specific_leaf_min_words: 7
heuristics:
  grouping_term_patterns: []
  subtype_series_patterns: []
""",
    )

    result = generate_priority_dashboard_report(
        candidates_path=candidates,
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        config_path=config,
    )

    summary = result["summary"]
    assert summary["already_curated"] == 6
    assert summary["already_curated_excluded_from_export"] == 6
    assert summary["remaining_candidates"] == 2
    assert summary["total_candidates"] == 8
    assert 0 < summary["coverage_percent"] < 100
    assert summary["coverage_percent"] == pytest.approx(75.0)

    # The table only ever holds the two exported rows, so the headline has to
    # say where the other six went rather than look like a rendering bug.
    html_report = (dashboard_dir / "priority.html").read_text(encoding="utf-8")
    assert "6 of them were dropped from the candidate export" in html_report


def test_generate_priority_dashboard_skips_category_section_without_category_data(
    tmp_path: Path,
) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    candidates = tmp_path / "candidates.json"
    config = tmp_path / "config.yaml"

    _write_json(
        candidates,
        [
            {
                "mondo_id": "MONDO:0002442",
                "label": "long QT syndrome",
                "definition": "Inherited repolarization disorder.",
                "synonyms": ["LQTS"],
                "parents": ["cardiac channelopathy"],
                "xrefs": ["OMIM:192500"],
                "child_count": 16,
            }
        ],
    )
    _write(
        config,
        """
weights: {}
caps: {}
thresholds:
  broad_parent_min_children: 4
  subtype_series_min_family_size: 2
  over_specific_leaf_min_words: 7
heuristics:
  grouping_term_patterns: []
  subtype_series_patterns: []
""",
    )

    generate_priority_dashboard_report(
        candidates_path=candidates,
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        config_path=config,
    )

    payload = json.loads((dashboard_dir / "priority.json").read_text(encoding="utf-8"))
    assert payload["category_summary"] == []

    html_report = (dashboard_dir / "priority.html").read_text(encoding="utf-8")
    assert "Category View" not in html_report


def test_priority_dashboard_annotates_nec_risk_candidates(tmp_path: Path) -> None:
    """NEC-risk annotation on the candidates a curator is about to pick up.

    Acceptance-criterion item 3 of #3889 asks for the high-NEC-risk disease
    classes to be surfaced on the priority dashboard. The collision corpus
    deliberately spans both the uncurated candidates and the curated KB, since
    the documented Temtamy incident had one member of the pair already curated.
    """
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    candidates = tmp_path / "candidates.json"
    config = tmp_path / "config.yaml"

    _write_yaml(
        kb_dir / "Marden-Walker_Syndrome.yaml",
        {
            "name": "Marden-Walker Syndrome",
            "disease_term": {
                "term": {"id": "MONDO:0008708", "label": "Marden-Walker syndrome"}
            },
        },
    )
    _write_json(
        candidates,
        [
            {
                "mondo_id": "MONDO:0018150",
                "label": "Walker-Warburg syndrome",
                "definition": "Severe congenital muscular dystrophy.",
                "synonyms": ["WWS"],
                "parents": ["congenital muscular dystrophy"],
                "xrefs": ["OMIM:236670"],
                "child_count": 2,
            },
            {
                "mondo_id": "MONDO:0007947",
                "label": "Marfan syndrome",
                "definition": "Systemic connective tissue disease.",
                "synonyms": ["marfan syndrome, classic form"],
                "parents": ["connective tissue disease"],
                "xrefs": ["OMIM:154700"],
                "child_count": 1,
            },
        ],
    )
    _write(
        config,
        """
weights: {}
caps: {}
thresholds:
  broad_parent_min_children: 4
  subtype_series_min_family_size: 2
  over_specific_leaf_min_words: 7
heuristics:
  grouping_term_patterns: []
  subtype_series_patterns: []
""",
    )

    generate_priority_dashboard_report(
        candidates_path=candidates,
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        config_path=config,
    )

    payload = json.loads((dashboard_dir / "priority.json").read_text(encoding="utf-8"))
    rows = {row["mondo_id"]: row for row in payload["rows"]}

    walker = rows["MONDO:0018150"]["nec_risk"]
    classes = {flag["risk_class"] for flag in walker}
    # "Walker" is shared with the curated Marden-Walker entry, which is only
    # visible if the corpus reaches into kb/ as well as the candidate export.
    assert "EPONYM_COLLISION" in classes
    assert "ACRONYM_AMBIGUITY" in classes
    collision = next(f for f in walker if f["risk_class"] == "EPONYM_COLLISION")
    assert collision["detail"] == ["Walker"]

    assert rows["MONDO:0007947"]["nec_risk"] == []
    assert payload["summary"]["nec_risk_candidates"] == 1

    html_report = (dashboard_dir / "priority.html").read_text(encoding="utf-8")
    assert "nec-pill" in html_report
    assert "research/nec_risk_disease_classes.md" in html_report
    assert "just preflight-dr" in html_report
    # Table rows are rendered client-side from the embedded payload, so the
    # trigger has to survive into that payload and into the pill helper the
    # row renderer calls -- a flag with no visible trigger would be useless.
    assert "necRiskPill" in html_report
    assert "EPONYM_COLLISION" in html_report


def test_acronym_only_candidates_are_recorded_but_not_badged(tmp_path: Path) -> None:
    """A badge on half the table would warn about nothing.

    A short all-caps synonym is a genuine NEC risk only if the DR query is made
    with the acronym, and a large share of MONDO terms carry one, so an
    acronym-only candidate stays out of the table badge and the headline count
    while remaining fully present in the payload.
    """
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    candidates = tmp_path / "candidates.json"
    config = tmp_path / "config.yaml"

    _write_json(
        candidates,
        [
            {
                "mondo_id": "MONDO:0004979",
                "label": "asthma",
                "definition": "Chronic airway inflammation.",
                "synonyms": ["BA"],
                "parents": ["respiratory system disease"],
                "xrefs": ["OMIM:600807"],
                "child_count": 3,
            }
        ],
    )
    _write(
        config,
        """
weights: {}
caps: {}
thresholds:
  broad_parent_min_children: 4
  subtype_series_min_family_size: 2
  over_specific_leaf_min_words: 7
heuristics:
  grouping_term_patterns: []
  subtype_series_patterns: []
""",
    )

    generate_priority_dashboard_report(
        candidates_path=candidates,
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        config_path=config,
    )

    payload = json.loads((dashboard_dir / "priority.json").read_text(encoding="utf-8"))
    row = payload["rows"][0]
    assert [flag["risk_class"] for flag in row["nec_risk"]] == ["ACRONYM_AMBIGUITY"]
    assert payload["summary"]["nec_risk_candidates"] == 0
