import json
from pathlib import Path

import yaml

from dismech.priority_dashboard import PRIORITY_BLOCK_END
from dismech.priority_dashboard import PRIORITY_BLOCK_START
from dismech.priority_dashboard import generate_priority_dashboard_report


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def _write_yaml(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def _write_json(path: Path, payload: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def test_generate_priority_dashboard_report_builds_pages_and_injects_link(
    tmp_path: Path,
) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    dashboard_index = dashboard_dir / "index.html"
    candidates = tmp_path / "candidates.json"
    config = tmp_path / "config.yaml"

    _write_yaml(
        kb_dir / "Noonan_Syndrome.yaml",
        {
            "name": "Noonan Syndrome",
            "disease_term": {
                "term": {"id": "MONDO:0018997", "label": "Noonan syndrome"}
            },
        },
    )
    _write_json(
        candidates,
        [
            {
                "mondo_id": "MONDO:0002442",
                "label": "long QT syndrome",
                "definition": "Inherited repolarization disorder.",
                "synonyms": ["LQTS", "long-qt syndrome"],
                "parents": ["cardiac channelopathy"],
                "xrefs": ["OMIM:192500", "Orphanet:101019"],
                "child_count": 16,
                "clingen_definitive_count": 3,
                "subset_match_count": 1,
                "orphanet_match_count": 1,
                "categories": ["Cardiac"],
            },
            {
                "mondo_id": "MONDO:0018997",
                "label": "Noonan syndrome",
                "definition": "RASopathy with congenital heart disease.",
                "synonyms": ["Noonan syndrome 1 spectrum"],
                "parents": ["RASopathy"],
                "xrefs": ["OMIM:163950", "Orphanet:648"],
                "child_count": 6,
                "clingen_definitive_count": 3,
                "clingen_strong_count": 1,
                "subset_match_count": 1,
                "orphanet_match_count": 1,
                "categories": ["Cardiac", "Developmental"],
            },
            {
                "mondo_id": "MONDO:0010342",
                "label": "autism, susceptibility to, X-linked 3",
                "definition": "MECP2-linked susceptibility signal.",
                "synonyms": ["AUTSX3"],
                "parents": ["neurodevelopmental disorder"],
                "xrefs": ["OMIM:300496"],
                "subset_match_count": 1,
                "categories": ["Neurodevelopmental"],
            },
        ],
    )
    _write(
        config,
        """
weights:
  missing_from_dismech: 35
  has_definition: 6
  synonym_count: 1.5
  xref_count: 0.5
  clingen_definitive_count: 12
  clingen_strong_count: 6
  subset_match_count: 5
  orphanet_match_count: 4
  broad_parent_bonus: 8
  subtype_series_penalty: -18
  grouping_term_penalty: -28
  over_specific_leaf_penalty: -10
  obsolete_penalty: -100
  already_curated_penalty: -80
caps:
  synonym_count: 5
  xref_count: 8
  clingen_definitive_count: 3
  clingen_strong_count: 3
  subset_match_count: 3
  orphanet_match_count: 3
thresholds:
  broad_parent_min_children: 4
  subtype_series_min_family_size: 2
  over_specific_leaf_min_words: 7
heuristics:
  grouping_term_patterns:
    - "\\\\bsusceptibility\\\\b"
    - "^obsolete\\\\b"
  subtype_series_patterns:
    - "^(?P<stem>.+?),\\\\s*[0-9]+[A-Za-z]?$"
    - "^(?P<stem>.+?)\\\\s+[0-9]+[A-Za-z]?$"
""",
    )
    _write(
        dashboard_index,
        """
<!DOCTYPE html>
<html>
<body>
  <section class="chart-card">
    <h2>Existing Section</h2>
  </section>
  <footer>Generated by linkml-data-qc</footer>
</body>
</html>
""",
    )

    result_1 = generate_priority_dashboard_report(
        candidates_path=candidates,
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        config_path=config,
        dashboard_index_path=dashboard_index,
    )
    result_2 = generate_priority_dashboard_report(
        candidates_path=candidates,
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        config_path=config,
        dashboard_index_path=dashboard_index,
    )

    assert result_1["summary"]["total_candidates"] == 3
    assert result_1["summary"]["already_curated"] == 1
    assert result_1["summary"]["remaining_candidates"] == 2
    assert result_1["summary"]["root_action_candidates"] == 1
    assert (dashboard_dir / "priority.html").exists()
    assert (dashboard_dir / "priority.json").exists()

    payload = json.loads((dashboard_dir / "priority.json").read_text(encoding="utf-8"))
    assert payload["summary"]["top_remaining_label"] == "long QT syndrome"
    assert payload["action_breakdown"][0]["action"] == "CURATE_ROOT_WITH_SUBTYPES"
    assert payload["category_summary"][0]["category"] == "Cardiac"
    assert payload["category_summary"][0]["remaining_candidates"] == 1
    assert payload["scoring"]["weights"]["missing_from_dismech"] == 35
    assert payload["scoring"]["thresholds"]["broad_parent_min_children"] == 4
    assert payload["rows"][0]["recommended_action"] == "CURATE_ROOT_WITH_SUBTYPES"

    html_report = (dashboard_dir / "priority.html").read_text(encoding="utf-8")
    assert "Top Uncurated Diseases" in html_report
    assert "Explore the Ranking" in html_report
    assert "Selected Candidate" in html_report
    assert "priority-dashboard-data" in html_report
    assert "long QT syndrome" in html_report
    assert "Category View" in html_report

    index_content = dashboard_index.read_text(encoding="utf-8")
    assert "priority.html" in index_content
    assert index_content.count(PRIORITY_BLOCK_START) == 1
    assert index_content.count(PRIORITY_BLOCK_END) == 1

    assert result_2["summary"]["remaining_candidates"] == 2
    assert dashboard_index.read_text(encoding="utf-8").count(PRIORITY_BLOCK_START) == 1


def test_generate_priority_dashboard_skips_category_section_without_category_data(
    tmp_path: Path,
) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    candidates = tmp_path / "candidates.json"
    config = tmp_path / "config.yaml"

    _write_json(
        candidates,
        [
            {
                "mondo_id": "MONDO:0002442",
                "label": "long QT syndrome",
                "definition": "Inherited repolarization disorder.",
                "synonyms": ["LQTS"],
                "parents": ["cardiac channelopathy"],
                "xrefs": ["OMIM:192500"],
                "child_count": 16,
            }
        ],
    )
    _write(
        config,
        """
weights: {}
caps: {}
thresholds:
  broad_parent_min_children: 4
  subtype_series_min_family_size: 2
  over_specific_leaf_min_words: 7
heuristics:
  grouping_term_patterns: []
  subtype_series_patterns: []
""",
    )

    generate_priority_dashboard_report(
        candidates_path=candidates,
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        config_path=config,
    )

    payload = json.loads((dashboard_dir / "priority.json").read_text(encoding="utf-8"))
    assert payload["category_summary"] == []

    html_report = (dashboard_dir / "priority.html").read_text(encoding="utf-8")
    assert "Category View" not in html_report
