from pathlib import Path

from dismech.qc_dashboard import (
    UNCURATED_BLOCK_END,
    UNCURATED_BLOCK_START,
    collect_uncurated_disease_references,
    generate_uncurated_dashboard_report,
)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def test_collect_uncurated_references_counts_linking_pages(tmp_path: Path) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    _write(
        kb_dir / "Acne_Vulgaris.yaml",
        """
name: Acne Vulgaris
disease_term:
  preferred_term: acne vulgaris
  term:
    id: MONDO:1000001
    label: acne vulgaris
differential_diagnoses:
  - name: Rosacea-like Dermatitis
    disease_term:
      preferred_term: Rosacea-like Dermatitis
      term:
        id: MONDO:1000999
        label: rosacea-like dermatitis
""",
    )
    _write(
        kb_dir / "Rosacea.yaml",
        """
name: Rosacea
disease_term:
  term:
    id: MONDO:1000002
    label: rosacea
""",
    )
    _write(
        kb_dir / "Psoriasis.yaml",
        """
name: Psoriasis
disease_term:
  term:
    id: MONDO:1000003
    label: psoriasis
has_subtypes:
  - name: Dermatitis overlap subtype
    subtype_term:
      preferred_term: Rosacea-like Dermatitis
      term:
        id: MONDO:1000999
        label: rosacea-like dermatitis
""",
    )

    rows = collect_uncurated_disease_references(kb_dir)

    assert len(rows) == 1
    row = rows[0]
    assert row["disease_name"] == "Rosacea-like Dermatitis"
    assert row["mondo_id"] == "MONDO:1000999"
    assert row["linking_pages_count"] == 2
    assert [page["name"] for page in row["linking_pages"]] == [
        "Acne Vulgaris",
        "Psoriasis",
    ]


def test_generate_report_injects_dashboard_link_idempotently(tmp_path: Path) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    dashboard_dir = tmp_path / "dashboard"
    dashboard_index = dashboard_dir / "index.html"

    _write(
        kb_dir / "Disease_A.yaml",
        """
name: Disease A
disease_term:
  term:
    id: MONDO:2000001
    label: disease a
has_subtypes:
  - name: Missing Disease
    subtype_term:
      term:
        id: MONDO:2000999
        label: missing disease
""",
    )
    _write(
        kb_dir / "Disease_B.yaml",
        """
name: Disease B
disease_term:
  term:
    id: MONDO:2000002
    label: disease b
""",
    )
    _write(
        dashboard_index,
        """
<!DOCTYPE html>
<html>
<body>
  <section class="chart-card">
    <h2>Existing Section</h2>
  </section>
  <footer>Generated by linkml-data-qc</footer>
</body>
</html>
""",
    )

    result_1 = generate_uncurated_dashboard_report(
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        dashboard_index_path=dashboard_index,
    )
    result_2 = generate_uncurated_dashboard_report(
        kb_dir=kb_dir,
        dashboard_dir=dashboard_dir,
        dashboard_index_path=dashboard_index,
    )

    assert result_1["summary"]["total_uncurated_disease_terms"] == 1
    assert result_1["summary"]["total_linking_pages"] == 1
    assert (dashboard_dir / "not_yet_curated.html").exists()
    assert (dashboard_dir / "not_yet_curated.json").exists()

    index_content = dashboard_index.read_text(encoding="utf-8")
    assert "not_yet_curated.html" in index_content
    assert index_content.count(UNCURATED_BLOCK_START) == 1
    assert index_content.count(UNCURATED_BLOCK_END) == 1

    # Second pass should detect existing block and keep a single injected section.
    assert result_2["summary"]["total_uncurated_disease_terms"] == 1
    assert dashboard_index.read_text(encoding="utf-8").count(UNCURATED_BLOCK_START) == 1


def test_duplicate_curated_mondo_id_is_not_reported_as_uncurated(tmp_path: Path) -> None:
    kb_dir = tmp_path / "kb" / "disorders"
    _write(
        kb_dir / "Variant_A.yaml",
        """
name: Variant A
disease_term:
  term:
    id: MONDO:3000001
    label: duplicate disease
""",
    )
    _write(
        kb_dir / "Variant_B.yaml",
        """
name: Variant B
disease_term:
  term:
    id: MONDO:3000001
    label: duplicate disease
""",
    )
    _write(
        kb_dir / "Source.yaml",
        """
name: Source
disease_term:
  term:
    id: MONDO:3000002
    label: source disease
differential_diagnoses:
  - name: Duplicate disease
    disease_term:
      term:
        id: MONDO:3000001
        label: duplicate disease
""",
    )

    rows = collect_uncurated_disease_references(kb_dir)
    assert rows == []
