"""Guard tests for the reader-facing AI-curation / not-medical-advice disclaimer.

Every page a reader can land on must carry the disclaimer, because the common
way DisMech is encountered is a single page reached from a search engine or an
external link — the project documentation is never seen. See
``docs/explanation/design-decisions.md`` §11 and ``docs/disclaimer.md``.

These tests exist so that a newly added template or site page cannot silently
ship without one.
"""

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = REPO_ROOT / "src" / "dismech" / "templates"

CSS_PARTIAL = TEMPLATE_DIR / "_disclaimer.css.j2"
HTML_PARTIAL = TEMPLATE_DIR / "_disclaimer.html.j2"

#: Hand-maintained (non-generated) site pages a reader can land on. Derived or
#: internal QC surfaces (``dashboard/``, the MkDocs output in ``elements/``,
#: ``frontpage-candidates/``) are deliberately excluded — see §11.
STATIC_PAGES = [
    "index.html",
    "app/index.html",
    "app/discussions/index.html",
    "app/models/index.html",
    "app/embeddings/index.html",
    "app/embeddings/mechanisms.html",
    "details/index.html",
]

#: Reader-facing pages built from a template string embedded in a script rather
#: than from ``src/dismech/templates/``, so the template glob cannot reach them.
#: The generator *and* its committed output are both checked, because the output
#: is regenerated by its own ``just`` target rather than by the ``generate-pages``
#: workflow and can go stale against the generator without anything noticing.
NON_JINJA_SURFACES = {
    "scripts/gen_nih_topics_summary.py": "pages/nih-topics/index.html",
}

#: sessionStorage key holding the reader's dismissal. sessionStorage is scoped to
#: a single tab and cleared when it closes, so the dismissal survives navigation
#: within a session but not a new tab or a later visit (issue #7421).
STORAGE_KEY = "dismech-disclaimer-dismissed"

#: Substrings that must appear in any rendering of the disclaimer, whether it
#: comes from the Jinja partial or from the inlined copy on a static page.
REQUIRED_PHRASES = [
    "AI-curated research resource",
    "not medical advice",
    "https://dismech.monarchinitiative.org/elements/disclaimer/",
]


def _full_page_templates() -> list[Path]:
    """Every full-page template (partials, which start with ``_``, excluded)."""
    return sorted(
        path
        for path in TEMPLATE_DIR.glob("*.html.j2")
        if not path.name.startswith("_")
    )


def test_disclaimer_partials_exist_and_state_both_points() -> None:
    assert CSS_PARTIAL.is_file(), f"missing {CSS_PARTIAL}"
    assert HTML_PARTIAL.is_file(), f"missing {HTML_PARTIAL}"

    html = HTML_PARTIAL.read_text()
    for phrase in REQUIRED_PHRASES:
        assert phrase in html, f"disclaimer partial is missing {phrase!r}"
    # The two substantive claims from issue #7182.
    assert "AI curation agents" in html
    assert "medical diagnosis or treatment" in html

    assert ".dismech-disclaimer" in CSS_PARTIAL.read_text()


def test_full_page_templates_exist() -> None:
    """Sanity check so a bad glob cannot make the tests below vacuous."""
    assert len(_full_page_templates()) >= 10


def _include_pattern(partial: str) -> re.Pattern[str]:
    """Match a Jinja include of ``partial`` regardless of quoting/spacing.

    Jinja treats ``{% include "x" %}`` and ``{%include 'x'%}`` identically, so
    the guard should be about the behaviour, not the formatting.
    """
    return re.compile(
        r"\{%-?\s*include\s+['\"]" + re.escape(partial) + r"['\"]\s*-?%\}"
    )


@pytest.mark.parametrize(
    "template", _full_page_templates(), ids=lambda path: path.name
)
def test_full_page_template_includes_disclaimer(template: Path) -> None:
    text = template.read_text()
    assert _include_pattern("_disclaimer.html.j2").search(
        text
    ), f"{template.name} does not include the disclaimer markup partial"
    assert _include_pattern("_disclaimer.css.j2").search(
        text
    ), f"{template.name} does not include the disclaimer style partial"


def test_non_jinja_generated_pages_carry_disclaimer() -> None:
    """Reader-facing pages built from inline templates in ``scripts/``.

    ``_full_page_templates`` only globs ``src/dismech/templates/``, so pages
    generated from a template string embedded in a script are out of its reach
    and need checking explicitly. Add to ``NON_JINJA_SURFACES`` when a new script
    starts emitting a reader-facing page.

    Both the generator *and* its committed output are checked. These pages are
    tracked in git and regenerated by their own ``just`` target rather than by
    the ``generate-pages`` workflow, so the output can go stale against the
    generator without anything noticing.
    """
    for generator, page in NON_JINJA_SURFACES.items():
        for name in (generator, page):
            path = REPO_ROOT / name
            assert path.is_file(), f"missing {name}"
            text = path.read_text()
            assert (
                'class="dismech-disclaimer"' in text
            ), f"{name} is a reader-facing page (or its generator) with no disclaimer"
            for phrase in REQUIRED_PHRASES:
                assert phrase in text, f"{name} disclaimer is missing {phrase!r}"


@pytest.mark.parametrize("page", STATIC_PAGES)
def test_static_site_page_carries_disclaimer(page: str) -> None:
    path = REPO_ROOT / page
    assert path.is_file(), f"missing {page}"
    text = path.read_text()
    assert (
        'class="dismech-disclaimer"' in text
    ), f"{page} does not carry the disclaimer markup"
    assert ".dismech-disclaimer {" in text, f"{page} does not carry the disclaimer styles"
    for phrase in REQUIRED_PHRASES:
        assert phrase in text, f"{page} disclaimer is missing {phrase!r}"


def _markup_surfaces() -> list[Path]:
    """Every file that renders the bar's markup.

    The Jinja partial, the hand-maintained pages with the markup inlined, and
    the non-Jinja generator together with its committed output.
    """
    return (
        [HTML_PARTIAL]
        + [REPO_ROOT / page for page in STATIC_PAGES]
        + [
            REPO_ROOT / name
            for pair in NON_JINJA_SURFACES.items()
            for name in pair
        ]
    )


def _style_surfaces() -> list[Path]:
    """Every file that carries the bar's styles."""
    return (
        [CSS_PARTIAL]
        + [REPO_ROOT / page for page in STATIC_PAGES]
        + [
            REPO_ROOT / name
            for pair in NON_JINJA_SURFACES.items()
            for name in pair
        ]
    )


def test_disclaimer_is_dismissible_for_the_session() -> None:
    """The bar carries a dismiss control, and dismissal lasts one session.

    §11 originally made the bar non-dismissible. Issue #7421 reversed that: a
    reader may close it, and the closed state is kept under the
    ``dismech-disclaimer-dismissed`` **sessionStorage** key, so it survives
    navigation within a tab but returns on a later visit.

    Two things must not regress. The scope: ``localStorage`` would silence the
    statement permanently, which is explicitly not what was wanted. And the
    control: a real focusable button with an accessible label, not the
    click-anywhere ``.notice-banner`` behaviour, which would fight the link
    inside the bar.
    """
    for path in _markup_surfaces():
        text = path.read_text()
        where = path.relative_to(REPO_ROOT)

        # Anchor on the markup itself — on static pages and in the generator the
        # class name also appears earlier, in the inlined stylesheet.
        start = text.index('<aside class="dismech-disclaimer"')
        end = text.index("</aside>", start)
        block = text[start:end]
        # The bar plus the script that immediately follows it. Storage assertions
        # are scoped to this, so an unrelated future localStorage feature
        # elsewhere on a page cannot fail this test with a misleading message.
        script = text[start : text.index("</script>", start)]

        assert (
            'class="dismech-disclaimer-dismiss"' in block
        ), f"{where}: the disclaimer has no dismiss control"
        assert (
            "<button" in block and 'type="button"' in block
        ), f"{where}: the dismiss control is not a real button"
        assert (
            'aria-label="Dismiss this disclaimer"' in block
        ), f"{where}: the dismiss control has no accessible label"
        assert (
            'title="Dismiss this disclaimer"' in block
        ), f"{where}: the bare glyph has no tooltip"
        assert "notice-banner" not in block, f"{where}: do not reuse .notice-banner"
        assert "onclick" not in block.lower(), f"{where}: use a listener, not onclick"

        assert (
            STORAGE_KEY in script
        ), f"{where}: dismissal is not recorded under the shared storage key"
        assert (
            "sessionStorage" in script
        ), f"{where}: dismissal does not survive navigation within a session"
        # Matches the API being *used*, not prose mentioning it — the partials
        # explain in a comment why localStorage was rejected.
        assert not re.search(
            r"window\.localStorage|(?<![A-Za-z.])localStorage\s*[.\[]", script
        ), (
            f"{where}: the disclaimer script must be session-scoped — "
            "localStorage would silence the disclaimer permanently"
        )


def test_dismissed_disclaimer_is_actually_hidden() -> None:
    """``[hidden]`` needs an explicit rule to beat the bar's own ``display``.

    The bar sets ``display: flex``, which outranks the user-agent rule for the
    ``hidden`` attribute — without this the dismiss button would set ``hidden``
    and nothing would visibly happen.
    """
    for path in _style_surfaces():
        text = path.read_text()
        assert ".dismech-disclaimer[hidden]" in text, (
            f"{path.relative_to(REPO_ROOT)}: no [hidden] rule, so dismissing the "
            "bar would not hide it"
        )


def test_generated_content_pages_keep_a_disclaimer_after_dismissal() -> None:
    """A dismissed page must not be left carrying no disclaimer at all.

    The top bar is dismissible for the session (#7421), so the page types a
    reader most often lands on from a search engine — disorder and module pages —
    also carry the non-dismissible ``_disclaimer_footer.html.j2`` line in their
    page footer. Those are the only full-page templates with a ``<footer>``; the
    gap on the rest is recorded in §11.
    """
    partial = TEMPLATE_DIR / "_disclaimer_footer.html.j2"
    assert partial.is_file(), f"missing {partial}"
    partial_text = partial.read_text()
    assert "not medical advice" in partial_text
    assert "https://dismech.monarchinitiative.org/elements/disclaimer/" in partial_text

    for name in ("disorder.html.j2", "module.html.j2"):
        template = TEMPLATE_DIR / name
        text = template.read_text()
        assert _include_pattern("_disclaimer_footer.html.j2").search(text), (
            f"{name} has a page footer but does not include the non-dismissible "
            "footer disclaimer"
        )
        footer_start = text.index('<footer class="page-footer">')
        footer_end = text.index("</footer>", footer_start)
        assert "_disclaimer_footer.html.j2" in text[footer_start:footer_end], (
            f"{name} includes the footer disclaimer outside its <footer>"
        )

    assert ".dismech-disclaimer-footer" in CSS_PARTIAL.read_text(), (
        "the footer disclaimer has no styles in _disclaimer.css.j2"
    )


def test_dismiss_control_is_hidden_without_javascript() -> None:
    """The button is revealed by the script, so no-JS readers see no dead control."""
    for path in _style_surfaces():
        text = path.read_text()
        where = path.relative_to(REPO_ROOT)
        # The generator's f-string-style template doubles its CSS braces, hence
        # the optional second brace.
        assert re.search(
            r"\.dismech-disclaimer-dismiss\s*\{\{?\s*display\s*:\s*none", text
        ), f"{where}: the dismiss control is not hidden by default"
        assert (
            ".dismech-disclaimer.is-dismissible .dismech-disclaimer-dismiss" in text
        ), f"{where}: nothing reveals the dismiss control once the script runs"


def test_canonical_disclaimer_doc_exists() -> None:
    doc = REPO_ROOT / "docs" / "disclaimer.md"
    assert doc.is_file(), "docs/disclaimer.md (the canonical disclaimer) is missing"
    text = doc.read_text()
    assert "AI-curated and AI-maintained" in text
    assert "not medical advice" in text.lower()

    nav = (REPO_ROOT / "mkdocs.yml").read_text()
    assert "disclaimer.md" in nav, "docs/disclaimer.md is not in the mkdocs nav"
