"""Logical coherence rules over pathophysiology node annotations.

A ``Pathophysiology`` node binds cell types to CL and processes to GO, and the
existing gates check each binding on its own: the CURIE resolves, the label is
canonical, the term is in the slot's dynamic enum. None of them asks whether
the bindings on one node are consistent *with each other*. So a node asserting
``CL:0000057 fibroblast`` alongside ``GO:0001837 epithelial to mesenchymal
transition`` is green everywhere while claiming that a fibroblast -- a cell
that is not epithelial -- undergoes the epithelial transition.

Curators already catch these by hand. ``Hypoplastic_Left_Heart_Syndrome``
carries a ten-line ``notes`` block explaining why an earlier draft's
``GO:0001837`` was wrong for an endocardial node, and ``Gastric_Adenocarcinoma``
another explaining why its E-cadherin node stops short of binding EMT. This
module makes that reasoning executable.

The formulation, and why it is inverted
---------------------------------------
The obvious rule is "EMT requires an epithelial cell; flag a node that has
none". It does not survive contact with CL. ``CL:0000646 basal cell`` and
``CL:0008036 extravillous trophoblast`` are textbook EMT substrates and neither
is an asserted subclass of ``CL:0000066 epithelial cell``, so that rule reports
correct curation as broken -- and every future gap in CL's is_a graph adds
another false accusation.

So a rule instead names the classes that *disqualify* a cell from being the
substrate, and fires only when **every** annotated cell type is disqualifying.
The claim is then positive -- these cells are connective-tissue cells, they are
not epithelium -- and an ontology gap costs a missed finding rather than a
wrong one. The "every" is equally deliberate: a node annotating both ends of a
transition (the alveolar epithelial cell that starts it, the myofibroblast it
becomes) is well curated, and an any-match rule would flag it.

Closures come from ``cache/closure/*.csv``, committed and regenerated by
``scripts/refresh_logical_rule_closures.py``, so evaluation is offline and
deterministic in the way every other KB gate here is. A rule whose closure is
not cached is reported by :func:`unusable_rules` and fails the check, rather
than evaluating to a clean pass it did not earn.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_RULES_PATH = ROOT / "conf" / "logical_rules.yaml"
DEFAULT_CLOSURE_DIR = ROOT / "cache" / "closure"

#: A node carrying this prefix in ``review_notes`` has been dispositioned by a
#: curator rather than left broken. The rule id must follow, then the reasoning.
WAIVER_PREFIX = "Logical rule waived:"

#: Words of recorded reasoning a waiver must carry after the sentinel and rule
#: id. Mirrors the floor ``check_environmental_evidence`` enforces: the sentence
#: alone does not waive, the argument does.
WAIVER_MIN_WORDS = 20


class RuleConfigError(ValueError):
    """The rule config or a closure cache could not be used as written."""


@dataclass(frozen=True)
class Rule:
    """One coherence rule, as read from ``conf/logical_rules.yaml``."""

    id: str
    summary: str
    processes: tuple[str, ...]
    disqualifying_cell_classes: tuple[str, ...]
    except_processes: tuple[str, ...] = ()
    remediation: str = ""

    @property
    def closure_roots(self) -> tuple[str, ...]:
        """Every term whose descendant closure this rule needs cached."""
        return tuple(
            dict.fromkeys(
                self.processes + self.except_processes + self.disqualifying_cell_classes
            )
        )


@dataclass(frozen=True)
class Finding:
    """One node that trips one rule."""

    rule_id: str
    path: Path
    node: str
    processes: tuple[str, ...]
    cell_types: tuple[str, ...]
    detail: str

    def format(self, root: Path | None = None) -> str:
        where = self.path
        if root is not None:
            try:
                where = self.path.relative_to(root)
            except ValueError:
                pass
        return f"{where}: {self.node!r} [{self.rule_id}] {self.detail}"


@dataclass
class Closures:
    """Descendant closures keyed by root CURIE, read from ``cache/closure``.

    ``members[root]`` always contains ``root`` itself, so ``is_descendant``
    answers the reflexive question a rule actually asks -- a node bound to
    ``GO:0001837`` itself trips an ``GO:0001837`` rule.
    """

    members: dict[str, set[str]] = field(default_factory=dict)
    labels: dict[str, str] = field(default_factory=dict)

    def has_root(self, root: str) -> bool:
        return root in self.members

    def is_descendant(self, term: str, root: str) -> bool:
        return term in self.members.get(root, ())

    def label(self, term: str) -> str:
        return self.labels.get(term, "")


def closure_filename(root: str) -> str:
    """``CL:0002320`` -> ``CL_0002320.csv``.

    Deliberately not ``terms.csv``: ``dismech.term_cache_integrity`` scans
    ``cache/*/terms.csv`` and would try to read a closure file as an ontology
    label cache, which it is not.
    """
    return root.replace(":", "_") + ".csv"


def load_rules(path: Path | None = None) -> list[Rule]:
    """Read and validate ``conf/logical_rules.yaml``."""
    path = path or DEFAULT_RULES_PATH
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except OSError as exc:
        raise RuleConfigError(f"cannot read rule config {path}: {exc}") from exc
    except yaml.YAMLError as exc:
        raise RuleConfigError(f"cannot parse rule config {path}: {exc}") from exc

    entries = raw.get("rules")
    if not isinstance(entries, list) or not entries:
        raise RuleConfigError(f"{path}: expected a non-empty `rules:` list")

    rules: list[Rule] = []
    seen: set[str] = set()
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            raise RuleConfigError(f"{path}: rule {index} is not a mapping")
        rule_id = entry.get("id")
        if not rule_id:
            raise RuleConfigError(f"{path}: rule {index} has no `id`")
        if rule_id in seen:
            raise RuleConfigError(f"{path}: duplicate rule id {rule_id!r}")
        seen.add(rule_id)
        processes = tuple(entry.get("processes") or ())
        disqualifying = tuple(entry.get("disqualifying_cell_classes") or ())
        if not processes:
            raise RuleConfigError(f"{path}: rule {rule_id!r} names no `processes`")
        if not disqualifying:
            raise RuleConfigError(
                f"{path}: rule {rule_id!r} names no `disqualifying_cell_classes`; "
                "a rule with no disqualifying class would flag every node "
                "carrying the process"
            )
        rules.append(
            Rule(
                id=rule_id,
                summary=str(entry.get("summary") or "").strip(),
                processes=processes,
                except_processes=tuple(entry.get("except_processes") or ()),
                disqualifying_cell_classes=disqualifying,
                remediation=str(entry.get("remediation") or "").strip(),
            )
        )
    return rules


def load_closures(
    roots: list[str] | tuple[str, ...], closure_dir: Path | None = None
) -> Closures:
    """Read the committed descendant closure for each of *roots*.

    A missing file is not an error here -- the caller reports it against the
    rule that needed it, which says more than a bare filename would.
    """
    closure_dir = closure_dir or DEFAULT_CLOSURE_DIR
    closures = Closures()
    for root in dict.fromkeys(roots):
        path = closure_dir / closure_filename(root)
        if not path.is_file():
            continue
        members = {root}
        with path.open(newline="", encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                curie = (row.get("curie") or "").strip()
                if not curie:
                    continue
                members.add(curie)
                label = (row.get("label") or "").strip()
                if label:
                    closures.labels.setdefault(curie, label)
        closures.members[root] = members
    return closures


def _terms(items: Any) -> list[tuple[str, str]]:
    """Pull ``(curie, label)`` out of a descriptor list, skipping unbound ones."""
    out: list[tuple[str, str]] = []
    for item in items or ():
        if not isinstance(item, dict):
            continue
        term = item.get("term")
        if not isinstance(term, dict):
            continue
        curie = term.get("id")
        if curie:
            out.append((str(curie), str(term.get("label") or "")))
    return out


def waiver_error(text: str | None, rule_id: str) -> str | None:
    """Return None when *text* waives *rule_id*, else why it does not.

    Returns the string ``"absent"`` when there is no waiver sentinel at all,
    which the caller uses to tell "no waiver offered" apart from "waiver
    offered but malformed" -- only the second is worth reporting.
    """
    value = (text or "").strip()
    if not value.startswith(WAIVER_PREFIX):
        return "absent"
    remainder = value[len(WAIVER_PREFIX) :].strip()
    claimed_id, _, justification = remainder.partition(".")
    claimed_id = claimed_id.strip()
    if claimed_id != rule_id:
        return (
            f"waiver names rule {claimed_id!r}, which is not {rule_id!r}; write "
            f"`{WAIVER_PREFIX} {rule_id}. <why>`"
        )
    words = len(justification.split())
    if words < WAIVER_MIN_WORDS:
        return (
            f"waiver for {rule_id!r} records {words} word(s) of reasoning, "
            f"below the {WAIVER_MIN_WORDS}-word floor; say which biology or "
            "which ontology gap makes the pairing correct here"
        )
    return None


def unusable_rules(rules: list[Rule], closures: Closures) -> list[str]:
    """Name the rules that cannot be evaluated, and the closures they lack.

    Checked once by the caller rather than per node: a missing closure means
    the check could not run at all, which is a different thing from a node
    being wrong, and repeating it 16,000 times says nothing extra.
    """
    problems: list[str] = []
    for rule in rules:
        missing = [r for r in rule.closure_roots if not closures.has_root(r)]
        if missing:
            problems.append(
                f"rule {rule.id!r} needs closures not in cache/closure: "
                f"{', '.join(missing)} (run `just refresh-logical-rule-closures`)"
            )
    return problems


def evaluate_node(
    node: dict[str, Any], rules: list[Rule], closures: Closures, path: Path
) -> list[Finding]:
    """Apply every rule to one pathophysiology node.

    A rule whose closures are not cached is skipped silently here; call
    :func:`unusable_rules` once up front to catch that, rather than inferring
    it from a clean run.
    """
    findings: list[Finding] = []

    processes = _terms(node.get("biological_processes"))
    cell_types = _terms(node.get("cell_types"))
    # A node with no cell annotation makes no claim about the substrate, so
    # there is nothing to contradict. This is most EMT nodes in the KB and is
    # a coverage gap, not a coherence defect -- a different check's business.
    if not processes or not cell_types:
        return findings

    node_name = str(node.get("name") or "<unnamed>")

    for rule in rules:
        if any(not closures.has_root(r) for r in rule.closure_roots):
            continue

        triggered = [
            (curie, label)
            for curie, label in processes
            if any(closures.is_descendant(curie, r) for r in rule.processes)
            and not any(closures.is_descendant(curie, r) for r in rule.except_processes)
        ]
        if not triggered:
            continue

        disqualified = [
            (curie, label)
            for curie, label in cell_types
            if any(
                closures.is_descendant(curie, r)
                for r in rule.disqualifying_cell_classes
            )
        ]
        if len(disqualified) != len(cell_types):
            continue

        problem = waiver_error(node.get("review_notes"), rule.id)
        if problem is None:
            continue
        if problem != "absent":
            findings.append(
                Finding(
                    rule_id=rule.id,
                    path=path,
                    node=node_name,
                    processes=tuple(c for c, _ in triggered),
                    cell_types=tuple(c for c, _ in disqualified),
                    detail=problem,
                )
            )
            continue

        proc = ", ".join(f"{c} {label}".strip() for c, label in triggered)
        cells = ", ".join(f"{c} {label}".strip() for c, label in disqualified)
        findings.append(
            Finding(
                rule_id=rule.id,
                path=path,
                node=node_name,
                processes=tuple(c for c, _ in triggered),
                cell_types=tuple(c for c, _ in disqualified),
                detail=(
                    f"annotates {proc}, but every cell type on the node "
                    f"({cells}) is disqualified as that process's substrate"
                ),
            )
        )

    return findings


def evaluate_entry(
    data: dict[str, Any], rules: list[Rule], closures: Closures, path: Path
) -> list[Finding]:
    """Apply every rule to every pathophysiology node in one KB entry."""
    findings: list[Finding] = []
    for node in data.get("pathophysiology") or ():
        if not isinstance(node, dict):
            continue
        findings.extend(evaluate_node(node, rules, closures, path))
    return findings
