"""Reproduce visible text from checksum-pinned publisher DOCX supplements."""

from __future__ import annotations

import argparse
import hashlib
import io
from pathlib import Path
import urllib.request
import xml.etree.ElementTree as ET
import zipfile

import yaml


def extract_docx_text(document: bytes) -> str:
    """Keep visible paragraph text, including table cells, in document order.

    Word/EndNote field instructions are not visible source text. They live in
    w:instrText, so selecting w:t excludes them while retaining displayed text.
    """
    with zipfile.ZipFile(io.BytesIO(document)) as archive:
        root = ET.fromstring(archive.read("word/document.xml"))
    ns = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
    paragraphs = [
        "".join(run.text or "" for run in paragraph.iter(ns + "t")).rstrip()
        for paragraph in root.iter(ns + "p")
    ]
    return "\n\n".join(p for p in paragraphs if p.strip()) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("data/literature_supplements/manifest.yaml"),
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        help="Use previously downloaded DOCX files instead of fetching their URLs.",
    )
    args = parser.parse_args()
    records = yaml.safe_load(args.manifest.read_text())["supplements"]
    for record in records:
        if args.source_dir:
            document = (args.source_dir / record["filename"]).read_bytes()
        else:
            request = urllib.request.Request(
                record["url"], headers={"User-Agent": "dismech-source-extraction"}
            )
            with urllib.request.urlopen(request, timeout=60) as response:
                document = response.read()
        digest = hashlib.sha256(document).hexdigest()
        if digest != record["sha256"]:
            raise ValueError(
                f"Publisher document checksum mismatch: {record['filename']}"
            )
        header = (
            f"# {record['title']}\n\n"
            f"Article: {record['article']}\n\n"
            f"Source: {record['url']}\n\n"
            "Generated by scripts/extract_literature_supplements.py from the "
            "checksum-pinned publisher DOCX. Visible paragraph text, including "
            "table cells, is preserved in document order. Hidden Word/EndNote "
            "field instructions are excluded.\n\n"
        )
        output = args.manifest.parent / record["output"]
        output.write_text(header + extract_docx_text(document))
        print(output)


if __name__ == "__main__":
    main()
