#!/usr/bin/env python3
"""Normalize Mermaid blocks generated by gen-doc for MkDocs rendering."""

from __future__ import annotations

import re
from pathlib import Path


def _clean_quoted_mermaid_text(line: str) -> str:
    """Remove markdown emphasis qualifiers inside quoted Mermaid strings."""

    def repl(match: re.Match[str]) -> str:
        text = match.group(1)
        # Example: "* _recommended_" -> "*"
        text = re.sub(r"\s+_[A-Za-z0-9]+_", "", text).strip()
        return f'"{text}"'

    return re.sub(r'"([^"]*)"', repl, line)


def fix_file(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    in_mermaid = False
    changed = False
    out_lines: list[str] = []

    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("```mermaid"):
            in_mermaid = True
            out_lines.append(line)
            continue
        if in_mermaid and stripped.startswith("```"):
            in_mermaid = False
            out_lines.append(line)
            continue

        if in_mermaid:
            fixed = _clean_quoted_mermaid_text(line)
            if fixed != line:
                changed = True
            out_lines.append(fixed)
        else:
            out_lines.append(line)

    if changed:
        path.write_text("".join(out_lines), encoding="utf-8")
    return changed


def main() -> None:
    root = Path("docs/elements")
    if not root.exists():
        return

    changed_count = 0
    for md_file in sorted(root.glob("*.md")):
        if fix_file(md_file):
            changed_count += 1

    print(f"Mermaid normalization updated {changed_count} files.")


if __name__ == "__main__":
    main()
