window.searchData = [
  {
    "model_key": "Crohn_Disease--computational-model-agora2-gut-microbiome-metabolic-models--0",
    "name": "AGORA2 Gut Microbiome Metabolic Models",
    "description": "Collection of 7,302 strain-resolved genome-scale metabolic reconstructions of human gut microorganisms. Enables modeling of dysbiosis-associated metabolic shifts in CD, including depletion of butyrate-producing Firmicutes (F. prausnitzii, Roseburia) and expansion of Enterobacteriaceae. Supports integration with host intestinal epithelial cell models.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "https://www.vmh.life/",
    "repository_host": "Virtual Metabolic Human",
    "publication": "PMID:36543475",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Crohn Disease",
    "disease_id": "MONDO:0005011",
    "category": "Complex",
    "parents": [
      "Inflammatory Bowel Disease",
      "Autoimmune Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Nature Biotechnology 2022 - includes strain-level resolution for studying CD-associated dysbiosis patterns",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Crohn_Disease.html#computational-model-agora2-gut-microbiome-metabolic-models",
    "source_file": "kb/disorders/Crohn_Disease.yaml"
  },
  {
    "model_key": "Diabetes_mellitus--computational-model-agora2-gut-microbiome-metabolic-models--2",
    "name": "AGORA2 Gut Microbiome Metabolic Models",
    "description": "Collection of 7,302 strain-resolved genome-scale metabolic reconstructions of human gut microorganisms. Enables personalized microbiome-host metabolic modeling by integrating with human metabolic models (Recon3D). Captures strain-level variation in SCFA production, bile acid metabolism, and drug biotransformation relevant to T2D.",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "https://www.vmh.life/",
    "repository_host": "Virtual Metabolic Human",
    "publication": "PMID:36658342",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Diabetes mellitus",
    "disease_id": "MONDO:0005015",
    "category": "Complex",
    "parents": [
      "endocrine pancreas disorder",
      "glucose metabolism disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [
      "PMID:36658342"
    ],
    "num_evidence": 1,
    "notes": "Nature Biotechnology 2022 - includes drug metabolism capabilities for 98 drugs; enables community-level FBA with MICOM",
    "creation_date": "2026-02-21T15:39:12Z",
    "page_url": "../../pages/disorders/Diabetes_mellitus.html#computational-model-agora2-gut-microbiome-metabolic-models",
    "source_file": "kb/disorders/Diabetes_Mellitus.yaml"
  },
  {
    "model_key": "Type_2_Diabetes_Mellitus--computational-model-agora2-gut-microbiome-metabolic-models--4",
    "name": "AGORA2 Gut Microbiome Metabolic Models",
    "description": "Collection of 7,302 strain-resolved genome-scale metabolic reconstructions of human gut microorganisms. Enables personalized microbiome-host metabolic modeling by integrating with human metabolic models (Recon3D). Captures strain-level variation in SCFA production, bile acid metabolism, and drug biotransformation relevant to T2D.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "https://www.vmh.life/",
    "repository_host": "Virtual Metabolic Human",
    "publication": "PMID:36543475",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Type 2 Diabetes Mellitus",
    "disease_id": "MONDO:0005148",
    "category": "Complex",
    "parents": [
      "Diabetes Mellitus",
      "Metabolic Disease",
      "Endocrine Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Nature Biotechnology 2022 - includes drug metabolism capabilities for 98 drugs; enables community-level FBA with MICOM",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Type_2_Diabetes_Mellitus.html#computational-model-agora2-gut-microbiome-metabolic-models",
    "source_file": "kb/disorders/Type_2_Diabetes_Mellitus.yaml"
  },
  {
    "model_key": "Ulcerative_Colitis--computational-model-agora2-gut-microbiome-metabolic-models--0",
    "name": "AGORA2 Gut Microbiome Metabolic Models",
    "description": "Collection of 7,302 strain-resolved genome-scale metabolic reconstructions of human gut microorganisms. Enables modeling of UC-associated dysbiosis including loss of keystone SCFA producers (F. prausnitzii, Roseburia, Eubacterium rectale) and expansion of pathobionts (Fusobacterium, Enterobacteriaceae). Supports colonocyte energy metabolism modeling.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "https://www.vmh.life/",
    "repository_host": "Virtual Metabolic Human",
    "publication": "PMID:36543475",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Ulcerative Colitis",
    "disease_id": "MONDO:0005101",
    "category": "Complex",
    "parents": [
      "Gastrointestinal Disease",
      "Autoimmune Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Nature Biotechnology 2022 - strain-level resolution for butyrate producer depletion studies",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Ulcerative_Colitis.html#computational-model-agora2-gut-microbiome-metabolic-models",
    "source_file": "kb/disorders/Ulcerative_Colitis.yaml"
  },
  {
    "model_key": "Parkinson's_Disease--computational-model-alpha-synuclein-aggregation-bst-model--0",
    "name": "Alpha-Synuclein Aggregation BST Model",
    "description": "Biochemical Systems Theory (BST) model of alpha-synuclein aggregation kinetics in dopaminergic neurons. Integrates dopamine metabolism, ubiquitin-proteasome system, and lysosomal degradation pathways. Simulates effects of oxidative stress and proteasome inhibition on synuclein accumulation.\n",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "BIOMD0000000575",
    "repository_url": "https://www.ebi.ac.uk/biomodels/BIOMD0000000575",
    "repository_host": "BioModels",
    "publication": "PMID:19136028",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Parkinson's Disease",
    "disease_id": "MONDO:0005180",
    "category": "Complex",
    "parents": [
      "Neurodegenerative Disease",
      "Movement Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Alpha-Synuclein Aggregation"
    ],
    "num_mechanisms": 1,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "First comprehensive kinetic model of PD-related protein aggregation",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Parkinson's_Disease.html#computational-model-alpha-synuclein-aggregation-bst-model",
    "source_file": "kb/disorders/Parkinsons_Disease.yaml"
  },
  {
    "model_key": "Parkinson's_Disease--computational-model-alpha-synuclein-prion-like-spreading-model--3",
    "name": "Alpha-Synuclein Prion-like Spreading Model",
    "description": "Network diffusion model simulating prion-like propagation of misfolded alpha-synuclein through brain connectome. Uses graph-theoretical approach to predict spatial patterns of neurodegeneration from initial seeding sites.\n",
    "model_type": "Agent Based",
    "model_type_raw": "AGENT_BASED",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Parkinson's Disease",
    "disease_id": "MONDO:0005180",
    "category": "Complex",
    "parents": [
      "Neurodegenerative Disease",
      "Movement Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Alpha-Synuclein Aggregation"
    ],
    "num_mechanisms": 1,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Predicts Braak staging patterns from connectivity-based spreading",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Parkinson's_Disease.html#computational-model-alpha-synuclein-prion-like-spreading-model",
    "source_file": "kb/disorders/Parkinsons_Disease.yaml"
  },
  {
    "model_key": "Parkinson's_Disease--computational-model-basal-ganglia-spiking-neural-network--2",
    "name": "Basal Ganglia Spiking Neural Network",
    "description": "Computational model of the basal ganglia circuit capturing dopamine-modulated dynamics between striatum, globus pallidus, subthalamic nucleus, and substantia nigra. Simulates pathological beta-band oscillations and motor dysfunction in PD.\n",
    "model_type": "Physiological",
    "model_type_raw": "PHYSIOLOGICAL",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:29666208",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Parkinson's Disease",
    "disease_id": "MONDO:0005180",
    "category": "Complex",
    "parents": [
      "Neurodegenerative Disease",
      "Movement Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Basal Ganglia Circuit Dysfunction"
    ],
    "num_mechanisms": 1,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Models circuit-level effects of dopamine depletion and DBS therapy",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Parkinson's_Disease.html#computational-model-basal-ganglia-spiking-neural-network",
    "source_file": "kb/disorders/Parkinsons_Disease.yaml"
  },
  {
    "model_key": "Immune_Checkpoint_Blockade_Module--computational-model-base-tumor-immune-physicell-model--0",
    "name": "Base Tumor-Immune PhysiCell Model",
    "description": "Grammar-based PhysiCell agent-based model of a heterogeneous tumor under immune surveillance. Immune cells chemotax toward tumor-derived signals, form physical contacts, and attempt contact-mediated killing, making this a useful executable baseline for the anti-tumor T cell response segment of this module.",
    "model_type": "Agent Based",
    "model_type_raw": "AGENT_BASED",
    "model_format": "C++/XML/CSV",
    "model_software": "PhysiCell",
    "base_model": "PhysiCell grammar manuscript release DOI:10.5281/zenodo.16285252",
    "model_id": "grammar_samples:v2.0.1/user_projects/tumor_immune_base",
    "repository_url": "https://github.com/PhysiCell-Models/grammar_samples/tree/v2.0.1/user_projects/tumor_immune_base",
    "repository_host": "GitHub",
    "publication": "DOI:10.1016/j.cell.2025.06.048",
    "runnable": "Reference only",
    "source_type": "Module",
    "source_name": "Immune Checkpoint Blockade Module",
    "disease_id": null,
    "category": "",
    "parents": [],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Official sample model from the manuscript-synced grammar_samples release. Most relevant to the \"Anti-Tumor T Cell Response\" and early immune-escape portions of this module.",
    "creation_date": "2026-03-21T00:00:00Z",
    "page_url": "../../pages/modules/immune_checkpoint_blockade.html#computational-model-base-tumor-immune-physicell-model",
    "source_file": "kb/modules/immune_checkpoint_blockade.yaml"
  },
  {
    "model_key": "Fabry_disease--computational-model-bi-atrial-in-silico-fabry-arrhythmia-model--0",
    "name": "Bi-atrial in silico Fabry arrhythmia model",
    "description": "Physiological bi-atrial simulation model parameterized with GLA p.N215S iPSC-derived atrial cardiomyocyte changes to evaluate P-wave morphology and atrial fibrillation vulnerability in early Fabry cardiac disease.\n",
    "model_type": "Physiological",
    "model_type_raw": "PHYSIOLOGICAL",
    "model_format": "Format not recorded",
    "model_software": "In silico bi-atrial electrophysiology modeling",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:40557493",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Fabry disease",
    "disease_id": "MONDO:0010526",
    "category": "Mendelian",
    "parents": [
      "Lysosomal storage diseases",
      "X-linked genetic disorders"
    ],
    "variables": [
      "P-wave morphology",
      "Atrial fibrillation vulnerability"
    ],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 2,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Atrial cardiomyocyte electrophysiological remodeling"
    ],
    "num_mechanisms": 1,
    "findings": [
      "Simulated atrial-cell changes reproduced early Fabry P-wave morphology changes and increased atrial fibrillation vulnerability."
    ],
    "num_findings": 1,
    "evidence_refs": [
      "PMID:40557493"
    ],
    "num_evidence": 1,
    "notes": "",
    "creation_date": "2026-01-08T17:12:45Z",
    "page_url": "../../pages/disorders/Fabry_disease.html#computational-model-bi-atrial-in-silico-fabry-arrhythmia-model",
    "source_file": "kb/disorders/Fabry_Disease.yaml"
  },
  {
    "model_key": "Fanconi_Anemia--computational-model-boolean-network-model-of-fa-brca-pathway--0",
    "name": "Boolean Network Model of FA/BRCA Pathway",
    "description": "A Boolean network model incorporating the FA/BRCA DNA repair pathway, checkpoint proteins, and alternative DNA repair pathways. Simulates ICL repair, checkpoint activation, and predicts which alternative repair pathways become active when the FA/BRCA pathway is defective. The largest network model incorporating a DNA repair pathway at time of publication.",
    "model_type": "Boolean Network",
    "model_type_raw": "BOOLEAN_NETWORK",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:22267503",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Fanconi_Anemia",
    "disease_id": "MONDO:0019391",
    "category": "Genetic",
    "parents": [
      "Bone Marrow Failure",
      "Congenital Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [
      "The model simulates ICL repair mediated by the FA/BRCA pathway",
      "Alternative DNA repair pathways are predicted to become active when FA/BRCA is defective",
      "Checkpoint protein activation patterns emerge from recurrent DNA damage"
    ],
    "num_findings": 3,
    "evidence_refs": [
      "PMID:22267503"
    ],
    "num_evidence": 1,
    "notes": "",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Fanconi_Anemia.html#computational-model-boolean-network-model-of-fa-brca-pathway",
    "source_file": "kb/disorders/Fanconi_Anemia.yaml"
  },
  {
    "model_key": "Primary_Ciliary_Dyskinesia--computational-model-cfd-model-of-mucociliary-clearance-under-ciliary-abnormalities--0",
    "name": "CFD model of mucociliary clearance under ciliary abnormalities",
    "description": "Three-dimensional computational fluid dynamics model of a bronchial airway-surface-liquid segment, using a two-layer model (Newtonian periciliary liquid beneath a nonlinear viscoelastic mucus layer) with the immersed-boundary method to represent cilia, to quantify how ciliary abnormalities (reduced beat, altered coordination, reduced density) degrade mucociliary clearance \u2014 the central mechanism of PCD.",
    "model_type": "Physiological",
    "model_type_raw": "PHYSIOLOGICAL",
    "model_format": "Format not recorded",
    "model_software": "in-house finite-difference / immersed-boundary solver",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "DOI:10.1016/j.jnnfm.2023.105029",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Primary_Ciliary_Dyskinesia",
    "disease_id": "MONDO:0016575",
    "category": "Genetic",
    "parents": [
      "Ciliopathy",
      "Respiratory Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Impaired Mucociliary Clearance"
    ],
    "num_mechanisms": 1,
    "findings": [
      "A two-layer airway-surface-liquid CFD model with immersed-boundary cilia quantifies the effect of various ciliary abnormalities on mucociliary clearance."
    ],
    "num_findings": 1,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "General CFD model of impaired mucociliary clearance rather than a genotype-specific PCD model; cited by DOI (no PubMed abstract available for snippet-level validation).",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Primary_Ciliary_Dyskinesia.html#computational-model-cfd-model-of-mucociliary-clearance-under-ciliary-abnormalities",
    "source_file": "kb/disorders/Primary_Ciliary_Dyskinesia.yaml"
  },
  {
    "model_key": "Familial_Long_QT_Syndrome--computational-model-cipa-ikr-dynamic-ord-proarrhythmia-model--1",
    "name": "CiPA IKr-Dynamic ORd Proarrhythmia Model",
    "description": "Regulatory in-silico proarrhythmia model built on the O'Hara-Rudy ORd model by replacing the I_Kr formulation with a Markov model of dynamic drug-hERG (I_Kr) binding. Combined with multi-channel pharmacology (up to seven currents), it computes the net-charge metric qNet to stratify drug-induced torsades de pointes (TdP) risk. This is the acquired (drug-induced) long QT / proarrhythmia arm and is the consensus cell model of the FDA/HESI CiPA initiative.",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "O'Hara-Rudy ORd human ventricular action potential model (PMID:21637795)",
    "model_id": "",
    "repository_url": "https://github.com/FDA/CiPA",
    "repository_host": "GitHub",
    "publication": "PMID:28878692",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Familial Long QT Syndrome",
    "disease_id": "MONDO:0019171",
    "category": "Genetic",
    "parents": [
      "Cardiac Arrhythmia",
      "Channelopathy"
    ],
    "variables": [
      "qNet"
    ],
    "variable_ids": [
      "qNet"
    ],
    "variable_terms": [
      "Torsade de pointes"
    ],
    "num_variables": 1,
    "perturbations": [
      "KCNH2"
    ],
    "perturbation_ids": [
      "hgnc:6251"
    ],
    "modeled_mechanisms": [
      "Torsades de Pointes"
    ],
    "num_mechanisms": 1,
    "findings": [
      "The CiPA initiative uses an in-silico cell model with multi-channel pharmacology to predict drug-induced torsades de pointes risk",
      "The qNet net-charge metric classifies drug-induced TdP risk across a range of concentrations and pacing rates"
    ],
    "num_findings": 2,
    "evidence_refs": [
      "PMID:28878692"
    ],
    "num_evidence": 1,
    "notes": "Consensus in-silico model of the FDA/HESI Comprehensive in vitro Proarrhythmia Assay (CiPA); reference implementation at github.com/FDA/CiPA. Optimized by Dutta et al. 2017 from the IKr-dynamic ORd model.",
    "creation_date": "2026-04-14T05:37:14Z",
    "page_url": "../../pages/disorders/Familial_Long_QT_Syndrome.html#computational-model-cipa-ikr-dynamic-ord-proarrhythmia-model",
    "source_file": "kb/disorders/Long_QT_Syndrome.yaml"
  },
  {
    "model_key": "Atrial_Fibrillation--computational-model-courtemanche-ramirez-nattel-human-atrial-action-potential-model--0",
    "name": "Courtemanche-Ramirez-Nattel human atrial action-potential model",
    "description": "Ionic-current kinetic model of the human atrial cardiomyocyte action potential used to examine rate adaptation and ion-current contributions to AF susceptibility. It models cellular electrophysiology, not whole-patient natural history or treatment outcomes.",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "Courtemanche-1998-human-atrial-AP",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:9688927",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Atrial Fibrillation",
    "disease_id": "MONDO:0004981",
    "category": "Complex",
    "parents": [
      "Cardiovascular Disease",
      "Cardiac Arrhythmia"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Atrial Electrical Remodeling"
    ],
    "num_mechanisms": 1,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [
      "PMID:9688927"
    ],
    "num_evidence": 1,
    "notes": "",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Atrial_Fibrillation.html#computational-model-courtemanche-ramirez-nattel-human-atrial-action-potential-model",
    "source_file": "kb/disorders/Atrial_Fibrillation.yaml"
  },
  {
    "model_key": "Fanconi_Anemia--computational-model-deep-learning-fa-core-complex-structure--3",
    "name": "Deep Learning FA Core Complex Structure",
    "description": "Integration of deep-learned residue distance predictions with Rosetta folding and automated cryo-EM map-guided assembly to determine the near-complete atomic structure of the Fanconi Anemia core complex (FAcc) E3 ubiquitin ligase from a 4.6 angstrom resolution cryo-EM map. Placed 5182 of 6557 residues, greatly expanding the structural model and enabling interpretation of disease-related mutations.",
    "model_type": "Machine Learning",
    "model_type_raw": "MACHINE_LEARNING",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:32939280",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Fanconi_Anemia",
    "disease_id": "MONDO:0019391",
    "category": "Genetic",
    "parents": [
      "Bone Marrow Failure",
      "Congenital Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [
      "Near-complete atomic model of FA core complex determined (5182 of 6557 residues placed)",
      "Deep learning overcame limitations of homology modeling for 4795 previously unmodeled residues",
      "Structure facilitates interpretation of disease-related mutational data"
    ],
    "num_findings": 3,
    "evidence_refs": [
      "PMID:32939280"
    ],
    "num_evidence": 1,
    "notes": "",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Fanconi_Anemia.html#computational-model-deep-learning-fa-core-complex-structure",
    "source_file": "kb/disorders/Fanconi_Anemia.yaml"
  },
  {
    "model_key": "Fanconi_Anemia--computational-model-dna-methylation-episignature-classifier--4",
    "name": "DNA Methylation Episignature Classifier",
    "description": "Machine learning classifier trained on genome-wide DNA methylation profiles from peripheral blood of FA patients. Identifies 82 differentially methylated CpG sites that distinguish FA from healthy individuals and other genetic disorders. The episignature is robust across complementation groups and tissue types, and can detect FA even in individuals with reverted phenotype due to gene conversion.",
    "model_type": "Machine Learning",
    "model_type_raw": "MACHINE_LEARNING",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:37865086",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Fanconi_Anemia",
    "disease_id": "MONDO:0019391",
    "category": "Genetic",
    "parents": [
      "Bone Marrow Failure",
      "Congenital Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [
      "82 CpG sites define an FA-specific DNA methylation signature",
      "Episignature validated across multiple complementation groups",
      "Can diagnose FA even in mosaic/reverted patients with normalized chromosome breakage"
    ],
    "num_findings": 3,
    "evidence_refs": [
      "PMID:37865086"
    ],
    "num_evidence": 1,
    "notes": "",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Fanconi_Anemia.html#computational-model-dna-methylation-episignature-classifier",
    "source_file": "kb/disorders/Fanconi_Anemia.yaml"
  },
  {
    "model_key": "Immune_Checkpoint_Blockade_Module--computational-model-extended-tumor-immune-physicell-model--1",
    "name": "Extended Tumor-Immune PhysiCell Model",
    "description": "Expanded grammar-based PhysiCell tumor-immune model with a richer set of immune-tumor interaction rules than the base example. This is a better executable analogue for adaptive immune resistance and state-dependent suppression within checkpoint-responsive tumors.",
    "model_type": "Agent Based",
    "model_type_raw": "AGENT_BASED",
    "model_format": "C++/XML/CSV",
    "model_software": "PhysiCell",
    "base_model": "PhysiCell grammar manuscript release DOI:10.5281/zenodo.16285252",
    "model_id": "grammar_samples:v2.0.1/user_projects/tumor_immune_extended",
    "repository_url": "https://github.com/PhysiCell-Models/grammar_samples/tree/v2.0.1/user_projects/tumor_immune_extended",
    "repository_host": "GitHub",
    "publication": "DOI:10.1016/j.cell.2025.06.048",
    "runnable": "Reference only",
    "source_type": "Module",
    "source_name": "Immune Checkpoint Blockade Module",
    "disease_id": null,
    "category": "",
    "parents": [],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Official sample model from the manuscript-synced grammar_samples release. Best treated as a reusable executable reference for checkpoint-sensitive tumor-immune interaction logic rather than a disease-specific digital twin.",
    "creation_date": "2026-03-21T00:00:00Z",
    "page_url": "../../pages/modules/immune_checkpoint_blockade.html#computational-model-extended-tumor-immune-physicell-model",
    "source_file": "kb/modules/immune_checkpoint_blockade.yaml"
  },
  {
    "model_key": "Sick_Sinus_Syndrome_2,_Autosomal_Dominant--computational-model-fabbri-severi-human-sinoatrial-node-cell-model-with-hcn4-mutation-induced-i-f-changes--0",
    "name": "Fabbri-Severi human sinoatrial node cell model with HCN4 mutation-induced I_f changes",
    "description": "A published in-silico risk-stratification study of SSS2. In-vitro biophysical data for HCN4 loss-of-function alleles were used to compute the charge carried by I_f during diastolic depolarization of a prerecorded human sinoatrial node action potential, and that quantity was used to drive the Fabbri-Severi model of a human sinoatrial node pacemaker cell. It is the computational counterpart of the funny-current node in this entry: it makes the qualitative claim (less diastolic I_f, slower firing) quantitative and allele-specific.",
    "model_type": "Physiological",
    "model_type_raw": "PHYSIOLOGICAL",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:37760888",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Sick Sinus Syndrome 2, Autosomal Dominant",
    "disease_id": "MONDO:0008102",
    "category": "Mendelian",
    "parents": [
      "Familial Sick Sinus Syndrome",
      "Channelopathy"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Reduced Funny Current and Slowed Diastolic Depolarization"
    ],
    "num_mechanisms": 1,
    "findings": [
      "The diastolic funny-current charge computed by action-potential clamp predicts both the simulated pacemaker rate of a human sinoatrial node cell model and the resting or minimum heart rate of HCN4 mutation carriers, making it a candidate risk-stratification measure for HCN4 loss-of-function sinus bradycardia."
    ],
    "num_findings": 1,
    "evidence_refs": [
      "PMID:37760888"
    ],
    "num_evidence": 1,
    "notes": "",
    "creation_date": "2026-08-17T00:00:00Z",
    "page_url": "../../pages/disorders/Sick_Sinus_Syndrome_2,_Autosomal_Dominant.html#computational-model-fabbri-severi-human-sinoatrial-node-cell-model-with-hcn4-mutation-induced-i-f-changes",
    "source_file": "kb/disorders/Sick_Sinus_Syndrome_2_Autosomal_Dominant.yaml"
  },
  {
    "model_key": "Phenylketonuria--computational-model-harvey-whole-body-pku-model--2",
    "name": "Harvey Whole-Body PKU Model",
    "description": "Sex-specific whole-body model for organ-resolved IEM biomarker prediction.",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "Harvey 1.0",
    "model_id": "",
    "repository_url": "https://www.vmh.life/",
    "repository_host": "Virtual Metabolic Human",
    "publication": "PMID:32463598",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Phenylketonuria",
    "disease_id": "MONDO:0009861",
    "category": "Genetic",
    "parents": [
      "Metabolic Disease",
      "Inborn Error of Metabolism"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [
      "PAH"
    ],
    "perturbation_ids": [
      "hgnc:8582"
    ],
    "modeled_mechanisms": [
      "Hepatic PAH Enzyme Deficiency",
      "Hyperphenylalaninemia"
    ],
    "num_mechanisms": 2,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [
      "PMID:32463598"
    ],
    "num_evidence": 1,
    "notes": "Whole-body WBM framework supports organ-resolved biomarker prediction in inherited metabolic disease.",
    "creation_date": "2025-12-19T14:27:56Z",
    "page_url": "../../pages/disorders/Phenylketonuria.html#computational-model-harvey-whole-body-pku-model",
    "source_file": "kb/disorders/Phenylketonuria.yaml"
  },
  {
    "model_key": "Crohn_Disease--computational-model-host-microbiome-multi-objective-optimization-model--2",
    "name": "Host-Microbiome Multi-Objective Optimization Model",
    "description": "Integrated metabolic model combining human intestinal epithelial cell (IEC) metabolism with gut microbiome community models. Uses multi-objective optimization to predict competition, mutualism, and neutralism between host and microbial metabolism. Models SCFA exchange, amino acid cross-feeding, and metabolic interactions disrupted in CD.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:38729159",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Crohn Disease",
    "disease_id": "MONDO:0005011",
    "category": "Complex",
    "parents": [
      "Inflammatory Bowel Disease",
      "Autoimmune Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "iScience 2024 - framework for quantifying host-microbiome metabolic crosstalk",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Crohn_Disease.html#computational-model-host-microbiome-multi-objective-optimization-model",
    "source_file": "kb/disorders/Crohn_Disease.yaml"
  },
  {
    "model_key": "Ulcerative_Colitis--computational-model-host-microbiome-multi-objective-optimization-model--2",
    "name": "Host-Microbiome Multi-Objective Optimization Model",
    "description": "Integrated metabolic model combining human colonic epithelial cell metabolism with gut microbiome community models. Predicts metabolic crosstalk disruption in UC, including butyrate deprivation effects on colonocyte beta-oxidation and tight junction maintenance.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:38729159",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Ulcerative Colitis",
    "disease_id": "MONDO:0005101",
    "category": "Complex",
    "parents": [
      "Gastrointestinal Disease",
      "Autoimmune Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "iScience 2024 - models host-microbiome metabolic interactions at community scale",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Ulcerative_Colitis.html#computational-model-host-microbiome-multi-objective-optimization-model",
    "source_file": "kb/disorders/Ulcerative_Colitis.yaml"
  },
  {
    "model_key": "Fanconi_Anemia--computational-model-machine-learning-drug-repurposing-drexml--2",
    "name": "Machine Learning Drug Repurposing (drexml)",
    "description": "Machine learning framework using multi-output regression and mechanistic signal transduction models to identify drug targets capable of regulating FA-related cell functionalities. The drexml tool predicts potential therapeutic targets by mapping external proteins to signaling circuits that trigger FA-related phenotypes, identifying over 20 potential drug targets and successfully predicting previously validated repurposed drugs.",
    "model_type": "Machine Learning",
    "model_type_raw": "MACHINE_LEARNING",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "https://github.com/loucerac/drexml",
    "repository_host": "GitHub",
    "publication": "PMID:31266445",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Fanconi_Anemia",
    "disease_id": "MONDO:0019391",
    "category": "Genetic",
    "parents": [
      "Bone Marrow Failure",
      "Congenital Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [
      "Over 20 potential therapeutic drug targets identified around the FA pathway",
      "Framework validated by successfully predicting previously known repurposed drugs in FA"
    ],
    "num_findings": 2,
    "evidence_refs": [
      "PMID:31266445",
      "PMID:38510973"
    ],
    "num_evidence": 2,
    "notes": "",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Fanconi_Anemia.html#computational-model-machine-learning-drug-repurposing-drexml",
    "source_file": "kb/disorders/Fanconi_Anemia.yaml"
  },
  {
    "model_key": "Crohn_Disease--computational-model-micom-community-metabolic-model--1",
    "name": "MICOM Community Metabolic Model",
    "description": "Metagenome-scale modeling framework for simulating metabolic interactions in the gut microbiota. Integrates dietary constraints and taxon abundances from metagenomic data to predict SCFA production deficits, cross-feeding network disruption, and pathobiont metabolic niches characteristic of CD dysbiosis.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "COBRApy",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:31964767",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Crohn Disease",
    "disease_id": "MONDO:0005011",
    "category": "Complex",
    "parents": [
      "Inflammatory Bowel Disease",
      "Autoimmune Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [
      "Community-level SCFA production is heterogeneous and highly individual-specific",
      "Model output reveals complex cross-feeding interactions that would be difficult to measure in vivo"
    ],
    "num_findings": 2,
    "evidence_refs": [
      "PMID:31964767"
    ],
    "num_evidence": 1,
    "notes": "mSystems 2020 - enables personalized microbiome metabolic modeling; applied to IBD cohorts",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Crohn_Disease.html#computational-model-micom-community-metabolic-model",
    "source_file": "kb/disorders/Crohn_Disease.yaml"
  },
  {
    "model_key": "Diabetes_mellitus--computational-model-micom-community-metabolic-model--3",
    "name": "MICOM Community Metabolic Model",
    "description": "Metagenome-scale modeling framework for simulating metabolic interactions in the gut microbiota. Integrates dietary constraints and taxon abundances from metagenomic data to predict personalized SCFA production, cross-feeding networks, and metabolic fluxes. Applied to T2D to study dysbiosis effects on butyrate production and glucose-insulin signaling.",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "COBRApy",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:31964767",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Diabetes mellitus",
    "disease_id": "MONDO:0005015",
    "category": "Complex",
    "parents": [
      "endocrine pancreas disorder",
      "glucose metabolism disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [
      "PMID:31964767"
    ],
    "num_evidence": 1,
    "notes": "mSystems 2020 - enables personalized microbiome metabolic modeling from 16S/metagenomics data",
    "creation_date": "2026-02-21T15:39:12Z",
    "page_url": "../../pages/disorders/Diabetes_mellitus.html#computational-model-micom-community-metabolic-model",
    "source_file": "kb/disorders/Diabetes_Mellitus.yaml"
  },
  {
    "model_key": "Type_2_Diabetes_Mellitus--computational-model-micom-community-metabolic-model--5",
    "name": "MICOM Community Metabolic Model",
    "description": "Metagenome-scale modeling framework for simulating metabolic interactions in the gut microbiota. Integrates dietary constraints and taxon abundances from metagenomic data to predict personalized SCFA production, cross-feeding networks, and metabolic fluxes. Applied to T2D to study dysbiosis effects on butyrate production and glucose-insulin signaling.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "COBRApy",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:31964767",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Type 2 Diabetes Mellitus",
    "disease_id": "MONDO:0005148",
    "category": "Complex",
    "parents": [
      "Diabetes Mellitus",
      "Metabolic Disease",
      "Endocrine Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "mSystems 2020 - enables personalized microbiome metabolic modeling from 16S/metagenomics data",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Type_2_Diabetes_Mellitus.html#computational-model-micom-community-metabolic-model",
    "source_file": "kb/disorders/Type_2_Diabetes_Mellitus.yaml"
  },
  {
    "model_key": "Ulcerative_Colitis--computational-model-micom-community-metabolic-model--1",
    "name": "MICOM Community Metabolic Model",
    "description": "Metagenome-scale modeling framework for simulating metabolic interactions in the gut microbiota. Models decreased butyrate production, impaired colonocyte energy metabolism, and Anna Karenina effect (increased community instability) observed in UC. Integrates with dietary intervention modeling.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "COBRApy",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:31964767",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Ulcerative Colitis",
    "disease_id": "MONDO:0005101",
    "category": "Complex",
    "parents": [
      "Gastrointestinal Disease",
      "Autoimmune Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "mSystems 2020 - enables personalized SCFA flux predictions from patient metagenomes",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Ulcerative_Colitis.html#computational-model-micom-community-metabolic-model",
    "source_file": "kb/disorders/Ulcerative_Colitis.yaml"
  },
  {
    "model_key": "Congenital_Hypothyroidism--computational-model-minimal-hypothalamic-pituitary-thyroid-feedback-model--0",
    "name": "Minimal Hypothalamic-Pituitary-Thyroid Feedback Model",
    "description": "A minimal two-state (TSH, free T4) ODE model of the hypothalamic-pituitary-thyroid negative-feedback loop, authored for dismech-perturb (analogous to the hand-authored CKD-MBD Antimony component; not a BioModels deposit). Pituitary TSH output is suppressed by free T4; the thyroid secretes T4 in proportion to TSH scaled by secretory capacity S_thy. Calibrated to a euthyroid steady state (TSH ~1.5 mU/L, free T4 ~15 pmol/L). Reducing S_thy reproduces primary congenital hypothyroidism (dysgenesis / dyshormonogenesis) with the compensatory TSH rise; reducing pituitary capacity reproduces central hypothyroidism (low free T4 with inappropriately normal TSH); and the exogenous levothyroxine term (LT4) restores euthyroidism, with over-replacement driving iatrogenic thyrotoxicosis.",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "SBML",
    "model_software": "Antimony/tellurium",
    "base_model": "",
    "model_id": "hpt_feedback_axis",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "",
    "runnable": "Runnable in-repo",
    "source_type": "Disorder",
    "source_name": "Congenital Hypothyroidism",
    "disease_id": "MONDO:0018612",
    "category": "Complex",
    "parents": [
      "hypothyroidism"
    ],
    "variables": [
      "TSH",
      "FT4"
    ],
    "variable_ids": [
      "TSH",
      "FT4"
    ],
    "variable_terms": [
      "Elevated circulating thyroid-stimulating hormone concentration",
      "Hyperthyroidism",
      "Hypothyroidism"
    ],
    "num_variables": 2,
    "perturbations": [
      "TPO",
      "TG",
      "DUOX2",
      "SLC5A5",
      "TSHR",
      "PAX8",
      "NKX2-1",
      "FOXE1"
    ],
    "perturbation_ids": [
      "hgnc:12015",
      "hgnc:11764",
      "hgnc:13273",
      "hgnc:11040",
      "hgnc:12373",
      "hgnc:8622",
      "hgnc:11825",
      "hgnc:3806"
    ],
    "modeled_mechanisms": [
      "Defective Thyroid Hormone Biosynthesis",
      "Thyroid Gland Dysgenesis",
      "Impaired Hypothalamic-Pituitary TSH Drive"
    ],
    "num_mechanisms": 3,
    "findings": [
      "Central hypothyroidism is modeled by reducing pituitary TSH secretion, producing low thyroid hormone with non-elevated TSH - the P_pit perturbation in this model.",
      "Levothyroxine replacement normalizes the thyroid axis in the simulator, the basis for the model's levothyroxine (LT4) treatment scenarios."
    ],
    "num_findings": 2,
    "evidence_refs": [
      "PMID:18844475"
    ],
    "num_evidence": 1,
    "notes": "Wired for dismech-perturb (models/hpt_feedback_axis.config.yaml; Antimony source models/hpt_feedback_axis.ant). The disease-severity dial is thyroid secretory capacity S_thy (baseline_gfr 1.0 = normal). Levothyroxine is an exogenous, TSH-independent T4 source (LT4); treatment scenarios titrate it from under-replacement (residual high TSH) through full replacement (euthyroid) to over-replacement (suppressed TSH, elevated free T4 = iatrogenic thyrotoxicosis). Thresholds are calibrated to model steady-state values, not clinical assay reference ranges.",
    "creation_date": "2026-05-14T20:54:37Z",
    "page_url": "../../pages/disorders/Congenital_Hypothyroidism.html#computational-model-minimal-hypothalamic-pituitary-thyroid-feedback-model",
    "source_file": "kb/disorders/Congenital_Hypothyroidism.yaml"
  },
  {
    "model_key": "Gout--computational-model-minimal-urate-homeostasis-model--0",
    "name": "Minimal Urate Homeostasis Model",
    "description": "A single-compartment ODE model of serum urate as the balance of production (purine turnover processed by xanthine oxidase) and elimination (renal/gut fractional excretion plus uricase activity), authored for dismech-perturb (like the CKD-MBD Antimony component; not a BioModels deposit). Calibrated to a normal serum urate of ~5 mg/dL with the monosodium-urate solubility limit (~6.8 mg/dL) as the hyperuricemia threshold. Reducing fractional excretion reproduces underexcretion hyperuricemia (>90% of primary cases); raising purine load reproduces overproduction. Urate-lowering therapies act on distinct nodes: xanthine-oxidase inhibitors reduce production, uricosurics raise excretion, and recombinant uricase adds direct urate degradation.",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "SBML",
    "model_software": "Antimony/tellurium",
    "base_model": "",
    "model_id": "urate_homeostasis",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "",
    "runnable": "Runnable in-repo",
    "source_type": "Disorder",
    "source_name": "Gout",
    "disease_id": "MONDO:0005393",
    "category": "Complex",
    "parents": [
      "Metabolic Disease",
      "Musculoskeletal Disease"
    ],
    "variables": [
      "Serum_Urate"
    ],
    "variable_ids": [
      "U"
    ],
    "variable_terms": [
      "Hyperuricemia",
      "Hypouricemia"
    ],
    "num_variables": 1,
    "perturbations": [
      "HPRT1",
      "PRPS1",
      "ABCG2",
      "SLC2A9",
      "SLC22A12"
    ],
    "perturbation_ids": [
      "hgnc:5157",
      "hgnc:9462",
      "hgnc:74",
      "hgnc:13446",
      "hgnc:17989"
    ],
    "modeled_mechanisms": [
      "Hyperuricemia"
    ],
    "num_mechanisms": 1,
    "findings": [
      "The monosodium-urate solubility limit (~6.8 mg/dL) defines the hyperuricemia threshold used for this model's Hyperuricemia phenotype mapping."
    ],
    "num_findings": 1,
    "evidence_refs": [
      "PMID:29904633"
    ],
    "num_evidence": 1,
    "notes": "Wired for dismech-perturb (models/urate_homeostasis.config.yaml; Antimony source models/urate_homeostasis.ant). The disease-severity dial is fractional excretion f_exc (baseline 1.0 = normal). Treatment scenarios model allopurinol and febuxostat (xanthine-oxidase inhibition, XO down), probenecid (uricosuric, f_exc up), and pegloticase (recombinant uricase, k_uricase up), plus a combination. URAT1/GLUT9 loss-of-function raise excretion (renal hypouricemia, protective), while ABCG2 loss lowers it. Thresholds use the ~6.8 mg/dL urate solubility limit; other bands are model-calibrated.",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Gout.html#computational-model-minimal-urate-homeostasis-model",
    "source_file": "kb/disorders/Gout.yaml"
  },
  {
    "model_key": "Phenylketonuria--computational-model-multi-compartment-pku-fba-model--0",
    "name": "Multi-compartment PKU FBA Model",
    "description": "Three-compartment FBA model with explicit blood-brain barrier transport for aromatic amino acids",
    "model_type": "Flux Balance Analysis",
    "model_type_raw": "FLUX_BALANCE_ANALYSIS",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "Recon-derived",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:36880400",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Phenylketonuria",
    "disease_id": "MONDO:0009861",
    "category": "Genetic",
    "parents": [
      "Metabolic Disease",
      "Inborn Error of Metabolism"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [
      "PAH"
    ],
    "perturbation_ids": [
      "hgnc:8582"
    ],
    "modeled_mechanisms": [
      "Competitive Large Neutral Amino Acid Transport at the Blood-Brain Barrier",
      "Reduced Dopamine Biosynthesis",
      "Reduced Serotonin Biosynthesis"
    ],
    "num_mechanisms": 3,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [
      "PMID:36880400"
    ],
    "num_evidence": 1,
    "notes": "Explains brain-specific pathology and why Phe restriction outperforms Tyr supplementation",
    "creation_date": "2025-12-19T14:27:56Z",
    "page_url": "../../pages/disorders/Phenylketonuria.html#computational-model-multi-compartment-pku-fba-model",
    "source_file": "kb/disorders/Phenylketonuria.yaml"
  },
  {
    "model_key": "Fanconi_Anemia--computational-model-multi-level-dynamical-modelling-of-scc-in-fa--1",
    "name": "Multi-level Dynamical Modelling of SCC in FA",
    "description": "A conceptual framework for multi-level dynamical modelling of squamous cell carcinoma development in Fanconi anemia, integrating longitudinal genome, proteome, and transcriptome data from a database of over 750 FA individuals. Proposes mechanistic models trained on multi-omic data from healthy and diseased tissue to detect early SCC signatures and predict tumorigenesis.",
    "model_type": "Unclassified",
    "model_type_raw": "",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:38028610",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Fanconi_Anemia",
    "disease_id": "MONDO:0019391",
    "category": "Genetic",
    "parents": [
      "Bone Marrow Failure",
      "Congenital Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [
      "Defines hallmarks of cancer specific to FA for model training",
      "Proposes using multi-omic data for early SCC signature detection",
      "Framework designed to predict experimentally testable tumorigenesis mechanisms"
    ],
    "num_findings": 3,
    "evidence_refs": [
      "PMID:38028610"
    ],
    "num_evidence": 1,
    "notes": "",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Fanconi_Anemia.html#computational-model-multi-level-dynamical-modelling-of-scc-in-fa",
    "source_file": "kb/disorders/Fanconi_Anemia.yaml"
  },
  {
    "model_key": "Anaplastic_Large_Cell_Lymphoma--computational-model-npm-alk-signaling-network-sensitivity-model--0",
    "name": "NPM-ALK Signaling-Network Sensitivity Model",
    "description": "A quantitative phenomenological ODE network uses Hill-type transfer functions and steady-state sensitivity analysis to rank control points for NPM-ALK-driven survival and proliferation. It predicts a predominant VAV1-CDC42 contribution to proliferation and RAS-MEK-ERK contribution to survival; these predictions require experimental validation.",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:27669408",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Anaplastic Large Cell Lymphoma",
    "disease_id": "MONDO:0020325",
    "category": "Cancer",
    "parents": [
      "Mature T-cell and NK-cell non-Hodgkin lymphoma"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Constitutive ALK Fusion Kinase Activity",
      "ALK-Driven STAT3 Activation"
    ],
    "num_mechanisms": 2,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [
      "PMID:27669408"
    ],
    "num_evidence": 1,
    "notes": "The model is literature-derived rather than patient-specific and reports relative steady-state activities, not validated clinical response predictions.",
    "creation_date": "2026-04-13T05:41:42Z",
    "page_url": "../../pages/disorders/Anaplastic_Large_Cell_Lymphoma.html#computational-model-npm-alk-signaling-network-sensitivity-model",
    "source_file": "kb/disorders/Anaplastic_Large_Cell_Lymphoma.yaml"
  },
  {
    "model_key": "Familial_Long_QT_Syndrome--computational-model-o-hara-rudy-ord-human-ventricular-action-potential-model--0",
    "name": "O'Hara-Rudy (ORd) Human Ventricular Action Potential Model",
    "description": "Foundational system of ordinary differential equations for the undiseased human ventricular cardiomyocyte action potential, fit to human myocyte data for the major ionic currents (I_CaL, I_Kr, I_Ks, I_K1, I_to, late I_Na, I_NaCa, I_NaK) with intracellular Ca2+ and CaMKII handling. Long QT syndrome is simulated by reducing repolarizing K+ conductance (I_Kr for LQT2, I_Ks for LQT1) or increasing the persistent late Na+ current (LQT3); each perturbation prolongs action potential duration and, during slow pacing, generates early afterdepolarizations, the cellular substrate for torsades de pointes.",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "CellML",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "ohara_rudy_2011",
    "repository_url": "https://models.cellml.org/e/71",
    "repository_host": "Physiome / CellML",
    "publication": "PMID:21637795",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Familial Long QT Syndrome",
    "disease_id": "MONDO:0019171",
    "category": "Genetic",
    "parents": [
      "Cardiac Arrhythmia",
      "Channelopathy"
    ],
    "variables": [
      "Membrane potential",
      "Action potential duration at 90% repolarization (APD90)"
    ],
    "variable_ids": [
      "v",
      "APD90"
    ],
    "variable_terms": [
      "Prolonged QTc interval"
    ],
    "num_variables": 2,
    "perturbations": [
      "KCNH2",
      "KCNQ1",
      "SCN5A"
    ],
    "perturbation_ids": [
      "hgnc:6251",
      "hgnc:6294",
      "hgnc:10593"
    ],
    "modeled_mechanisms": [
      "Prolonged Ventricular Action Potential Duration",
      "Early Afterdepolarizations"
    ],
    "num_mechanisms": 2,
    "findings": [
      "I_Kr block during slow pacing induces early afterdepolarizations in the model, the cellular trigger for torsades de pointes in LQT2 and drug-induced long QT"
    ],
    "num_findings": 1,
    "evidence_refs": [
      "PMID:21637795"
    ],
    "num_evidence": 1,
    "notes": "CellML encoding in the Physiome Model Repository (exposure e/71); original MATLAB from the Rudy Lab. Endocardial, midmyocardial, and epicardial cell variants are provided. Base model for the CiPA IKr-dynamic ORd and ToR-ORd refinements below.",
    "creation_date": "2026-04-14T05:37:14Z",
    "page_url": "../../pages/disorders/Familial_Long_QT_Syndrome.html#computational-model-o-hara-rudy-ord-human-ventricular-action-potential-model",
    "source_file": "kb/disorders/Long_QT_Syndrome.yaml"
  },
  {
    "model_key": "Diabetes_mellitus--computational-model-pancreatic-beta-cell-genome-scale-metabolic-model--0",
    "name": "Pancreatic Beta Cell Genome-Scale Metabolic Model",
    "description": "First comprehensive genome-scale metabolic reconstruction of human pancreatic beta cells, integrating transcriptomic data from healthy and type 2 diabetic islets. The model captures beta cell-specific metabolic pathways and identifies metabolic alterations in T2D including impaired glucose-stimulated insulin secretion mechanisms.",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:35276551",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Diabetes mellitus",
    "disease_id": "MONDO:0005015",
    "category": "Complex",
    "parents": [
      "endocrine pancreas disorder",
      "glucose metabolism disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [
      "PMID:35276551"
    ],
    "num_evidence": 1,
    "notes": "PLOS Computational Biology 2022 - context-specific reconstruction using RNA-seq from healthy and T2D beta cells",
    "creation_date": "2026-02-21T15:39:12Z",
    "page_url": "../../pages/disorders/Diabetes_mellitus.html#computational-model-pancreatic-beta-cell-genome-scale-metabolic-model",
    "source_file": "kb/disorders/Diabetes_Mellitus.yaml"
  },
  {
    "model_key": "Type_2_Diabetes_Mellitus--computational-model-pancreatic-beta-cell-genome-scale-metabolic-model--1",
    "name": "Pancreatic Beta Cell Genome-Scale Metabolic Model",
    "description": "First comprehensive genome-scale metabolic reconstruction of human pancreatic beta cells, integrating transcriptomic data from healthy and type 2 diabetic islets. The model captures beta cell-specific metabolic pathways and identifies metabolic alterations in T2D including impaired glucose-stimulated insulin secretion mechanisms.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:35276551",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Type 2 Diabetes Mellitus",
    "disease_id": "MONDO:0005148",
    "category": "Complex",
    "parents": [
      "Diabetes Mellitus",
      "Metabolic Disease",
      "Endocrine Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "PLOS Computational Biology 2022 - context-specific reconstruction using RNA-seq from healthy and T2D beta cells",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Type_2_Diabetes_Mellitus.html#computational-model-pancreatic-beta-cell-genome-scale-metabolic-model",
    "source_file": "kb/disorders/Type_2_Diabetes_Mellitus.yaml"
  },
  {
    "model_key": "Type_2_Diabetes_Mellitus--computational-model-pbpk-model-for-glp-1-receptor-agonists--3",
    "name": "PBPK Model for GLP-1 Receptor Agonists",
    "description": "Physiologically-based pharmacokinetic model for GLP-1 receptor agonists (semaglutide, tirzepatide) in T2D patients. Incorporates drug absorption, distribution, and receptor binding kinetics to optimize dosing regimens.\n",
    "model_type": "Physiological",
    "model_type_raw": "PHYSIOLOGICAL",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Type 2 Diabetes Mellitus",
    "disease_id": "MONDO:0005148",
    "category": "Complex",
    "parents": [
      "Diabetes Mellitus",
      "Metabolic Disease",
      "Endocrine Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Used in clinical trial design and dose optimization for incretin-based therapies",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Type_2_Diabetes_Mellitus.html#computational-model-pbpk-model-for-glp-1-receptor-agonists",
    "source_file": "kb/disorders/Type_2_Diabetes_Mellitus.yaml"
  },
  {
    "model_key": "Pancreatic_Ductal_Adenocarcinoma--computational-model-pdac-caf-mediated-invasion-physicell-model--0",
    "name": "PDAC CAF-Mediated Invasion PhysiCell Model",
    "description": "Grammar-based PhysiCell agent-based model of pancreatic ductal adenocarcinoma neoplastic cells and cancer-associated fibroblasts. The model encodes fibroblast-mediated invasion, epithelial-mesenchymal state switching, and ECM-dependent motility tradeoffs using human-interpretable cell rules informed by PDAC spatial transcriptomics and coculture data.",
    "model_type": "Agent Based",
    "model_type_raw": "AGENT_BASED",
    "model_format": "C++/XML/CSV",
    "model_software": "PhysiCell",
    "base_model": "PhysiCell grammar manuscript release DOI:10.5281/zenodo.16285252",
    "model_id": "grammar_samples:v2.0.1/user_projects/epi_caf_invasion",
    "repository_url": "https://github.com/PhysiCell-Models/grammar_samples/tree/v2.0.1/user_projects/epi_caf_invasion",
    "repository_host": "GitHub",
    "publication": "DOI:10.1016/j.cell.2025.06.048",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Pancreatic Ductal Adenocarcinoma",
    "disease_id": "MONDO:0005184",
    "category": "",
    "parents": [
      "pancreatic cancer"
    ],
    "variables": [
      "inflammatory_signal",
      "ecm",
      "epithelial_normal_cells",
      "mesenchymal_normal_cells",
      "fibroblast_cells",
      "epithelial_tumor_cells",
      "mesenchymal_tumor_cells"
    ],
    "variable_ids": [
      "inflammatory_signal",
      "ecm",
      "epithelial_normal",
      "mesenchymal_normal",
      "fibroblast",
      "epithelial_tumor",
      "mesenchymal_tumor"
    ],
    "variable_terms": [
      "Extracellular matrix",
      "epithelial cell",
      "epithelial tumor cell",
      "fibroblast",
      "mesenchymal cell",
      "mesenchymal tumor cell"
    ],
    "num_variables": 7,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Desmoplastic Stroma"
    ],
    "num_mechanisms": 1,
    "findings": [
      "ECM increases epithelial-to-mesenchymal switching of tumor epithelial cells in the executable PDAC invasion model.",
      "Fibroblast migration is explicitly controlled by ECM-dependent rules in the invasion model."
    ],
    "num_findings": 2,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Manuscript-synced sample model from the official PhysiCell grammar_samples release. Relevant configs include `config/PhysiCell_settings_PDAC.xml`, the rule table in `config/cell_rules.csv`, and coculture initial conditions under `config/ics/`.",
    "creation_date": "2026-03-06T00:00:00Z",
    "page_url": "../../pages/disorders/Pancreatic_Ductal_Adenocarcinoma.html#computational-model-pdac-caf-mediated-invasion-physicell-model",
    "source_file": "kb/disorders/Pancreatic_Ductal_Adenocarcinoma.yaml"
  },
  {
    "model_key": "Pancreatic_Ductal_Adenocarcinoma--computational-model-pdac-immunotherapy-physicell-model--1",
    "name": "PDAC Immunotherapy PhysiCell Model",
    "description": "Grammar-based PhysiCell agent-based PDAC tumor-immune model initialized from PDAC tissue compositions. The model simulates combination therapy with GVAX, nivolumab, and urelumab across heterogeneous baseline microenvironment states and is a strong executable analogue of PDAC immune-excluded ecology.",
    "model_type": "Agent Based",
    "model_type_raw": "AGENT_BASED",
    "model_format": "C++/XML/CSV",
    "model_software": "PhysiCell",
    "base_model": "PhysiCell grammar manuscript release DOI:10.5281/zenodo.16285252",
    "model_id": "grammar_samples:v2.0.1/user_projects/pdac_therapy",
    "repository_url": "https://github.com/PhysiCell-Models/grammar_samples/tree/v2.0.1/user_projects/pdac_therapy",
    "repository_host": "GitHub",
    "publication": "DOI:10.1016/j.cell.2025.06.048",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Pancreatic Ductal Adenocarcinoma",
    "disease_id": "MONDO:0005184",
    "category": "",
    "parents": [
      "pancreatic cancer"
    ],
    "variables": [
      "oxygen",
      "debris",
      "pro_inflammatory_factor",
      "anti_inflammatory_factor",
      "PD-L1lo_tumor_cells",
      "PD-L1hi_tumor_cells",
      "macrophages",
      "PD-1hi_CD137lo_CD8_T_cells",
      "PD-1lo_CD137lo_CD8_T_cells",
      "PD-1hi_CD137hi_CD8_T_cells",
      "PD-1lo_CD137hi_CD8_T_cells",
      "PD-1hi_CD4_T_cells",
      "PD-1lo_CD4_T_cells"
    ],
    "variable_ids": [
      "oxygen",
      "debris",
      "pro-inflammatory factor",
      "anti-inflammatory factor",
      "PD-L1lo_tumor",
      "PD-L1hi_tumor",
      "macrophage",
      "PD-1hi_CD137lo_CD8_Tcell",
      "PD-1lo_CD137lo_CD8_Tcell",
      "PD-1hi_CD137hi_CD8_Tcell",
      "PD-1lo_CD137hi_CD8_Tcell",
      "PD-1hi_CD4_Tcell",
      "PD-1lo_CD4_Tcell"
    ],
    "variable_terms": [
      "PD-1-high CD137-high CD8 T cell",
      "PD-1-high CD137-low CD8 T cell",
      "PD-1-high CD4 T cell",
      "PD-1-low CD137-high CD8 T cell",
      "PD-1-low CD137-low CD8 T cell",
      "PD-1-low CD4 T cell",
      "Programmed cell death 1 ligand 1",
      "dioxygen",
      "epithelial tumor cell",
      "macrophage"
    ],
    "num_variables": 13,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Immune Evasion"
    ],
    "num_mechanisms": 1,
    "findings": [
      "Contact with PD-L1-high tumor cells reduces CD8 T-cell migration in the executable PDAC immunotherapy model.",
      "Anti-inflammatory signals decrease CD8 T-cell attack against tumor cells in the executable PDAC immunotherapy model.",
      "Macrophage oxygen sensing controls pro- versus anti-inflammatory factor secretion in the executable PDAC immunotherapy model."
    ],
    "num_findings": 3,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Manuscript-synced sample model from the official PhysiCell grammar_samples release. Therapy-specific initial-condition files are stored in `config/ic_cells/`, and the core executable interaction logic is in `config/cell_rules.csv`.",
    "creation_date": "2026-03-06T00:00:00Z",
    "page_url": "../../pages/disorders/Pancreatic_Ductal_Adenocarcinoma.html#computational-model-pdac-immunotherapy-physicell-model",
    "source_file": "kb/disorders/Pancreatic_Ductal_Adenocarcinoma.yaml"
  },
  {
    "model_key": "CKD-Mineral_Bone_Disorder--computational-model-peterson-riggs-calcium-homeostasis-and-bone-remodeling-model--0",
    "name": "Peterson-Riggs Calcium Homeostasis and Bone Remodeling Model",
    "description": "Physiologically based ODE model of integrated calcium homeostasis and bone remodeling. Includes PTH, calcitriol, calcium, phosphate, and bone remodeling markers (osteoblasts, osteoclasts, RANKL/OPG). Describes hypoparathyroidism, hyperparathyroidism, renal insufficiency, PTH 1-34 administration, and RANKL inhibition. Foundation model for CKD-MBD simulations.",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "SBML",
    "model_software": "COPASI",
    "base_model": "",
    "model_id": "BIOMD0000000613",
    "repository_url": "https://www.ebi.ac.uk/biomodels/BIOMD0000000613",
    "repository_host": "BioModels",
    "publication": "PMID:19732857",
    "runnable": "Runnable in-repo",
    "source_type": "Disorder",
    "source_name": "CKD-Mineral Bone Disorder",
    "disease_id": null,
    "category": "Complex",
    "parents": [
      "Renal Disease",
      "Metabolic Bone Disease"
    ],
    "variables": [
      "Plasma_Ca",
      "Plasma_PO4",
      "Plasma_PTH",
      "Plasma_Calcitriol",
      "BMD",
      "Osteoclasts",
      "Osteoblasts",
      "FGF23",
      "Soluble_Klotho",
      "Vascular_Calcification",
      "Sclerostin",
      "CaPO4_Product"
    ],
    "variable_ids": [
      "P",
      "ECCPhos",
      "PTH",
      "B",
      "Qbone",
      "OC",
      "OB",
      "FGF23",
      "sKlotho",
      "VascCa",
      "SOST",
      "CaPO4_product"
    ],
    "variable_terms": [
      "Arterial calcification",
      "Calciphylaxis",
      "Calcitriol",
      "Calcium",
      "Fibroblast growth factor 23",
      "Intact PTH",
      "Left ventricular hypertrophy",
      "Pathologic fracture",
      "Phosphate",
      "Proximal muscle weakness",
      "Reduced bone mineral density",
      "Serum 1,25-dihydroxyvitamin D",
      "Serum calcium",
      "Serum phosphate",
      "Short stature"
    ],
    "num_variables": 12,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [
      "Model appropriately describes plasma PTH, calcitriol, calcium, phosphate, and bone remodeling markers across a broad range of clinical conditions",
      "Renal insufficiency simulation reproduces secondary hyperparathyroidism and bone loss",
      "Provides platform for hypothesis testing of PTH, vitamin D, and RANKL pathway interventions"
    ],
    "num_findings": 3,
    "evidence_refs": [
      "PMID:19732857"
    ],
    "num_evidence": 1,
    "notes": "Key validatable outputs: serum Ca, PO4, PTH, calcitriol, BMD. Genetic-validation anchors include CASR and RGS14 loci from CKD cohort data. Clinically validatable against CRIC mineral-marker data.",
    "creation_date": "2026-03-05T15:32:43Z",
    "page_url": "../../pages/disorders/CKD-Mineral_Bone_Disorder.html#computational-model-peterson-riggs-calcium-homeostasis-and-bone-remodeling-model",
    "source_file": "kb/disorders/CKD-Mineral_Bone_Disorder.yaml"
  },
  {
    "model_key": "CKD-Mineral_Bone_Disorder--computational-model-peterson-riggs-ckd-mbd-multiscale-extension--1",
    "name": "Peterson-Riggs CKD-MBD Multiscale Extension",
    "description": "Extension of the Peterson-Riggs calcium homeostasis model to simulate progressive CKD over a 10-year course, including evolution of secondary hyperparathyroidism from diminished renal phosphate clearance. Links bone remodeling markers with BMD formation and elimination rates. Includes simulated interventions with calcimimetics and calcitriol.",
    "model_type": "Physiological",
    "model_type_raw": "PHYSIOLOGICAL",
    "model_format": "SBML",
    "model_software": "COPASI",
    "base_model": "Peterson-Riggs 2010 (BIOMD0000000613)",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:22232752",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "CKD-Mineral Bone Disorder",
    "disease_id": null,
    "category": "Complex",
    "parents": [
      "Renal Disease",
      "Metabolic Bone Disease"
    ],
    "variables": [
      "Plasma_Ca",
      "Plasma_PO4",
      "Plasma_PTH",
      "BMD_lumbar",
      "GFR",
      "Bone_Remodeling_Marker"
    ],
    "variable_ids": [
      "P",
      "ECCPhos",
      "PTH",
      "Qbone",
      "GFR"
    ],
    "variable_terms": [
      "Estimated GFR",
      "Intact PTH",
      "Reduced bone mineral density",
      "Serum alkaline phosphatase",
      "Serum calcium",
      "Serum phosphate"
    ],
    "num_variables": 6,
    "perturbations": [
      "CASR"
    ],
    "perturbation_ids": [
      "hgnc:1514"
    ],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [
      "Predicted lumbar spine BMD losses at GFR 58, 39, and 16 mL/min of -0.98%, -3.0%, and -6.5% respectively, compared to observed values of -0.5%, -4.0%, and -8.1%",
      "Simulated calcimimetic intervention reduces PTH and attenuates BMD loss",
      "Simulated calcitriol intervention normalizes calcium but with risk of hyperphosphatemia"
    ],
    "num_findings": 3,
    "evidence_refs": [
      "PMID:22232752"
    ],
    "num_evidence": 1,
    "notes": "Multiscale model linking molecular/cellular bone remodeling to organ-level mineral homeostasis across progressive CKD stages. Validates against clinical BMD data stratified by GFR.",
    "creation_date": "2026-03-05T15:32:43Z",
    "page_url": "../../pages/disorders/CKD-Mineral_Bone_Disorder.html#computational-model-peterson-riggs-ckd-mbd-multiscale-extension",
    "source_file": "kb/disorders/CKD-Mineral_Bone_Disorder.yaml"
  },
  {
    "model_key": "Renal_Cell_Carcinoma--computational-model-rcc-3d-agent-based-learning-model--0",
    "name": "RCC 3D Agent-Based Learning Model",
    "description": "Spatial three-dimensional agent-based simulation of established renal cell carcinoma, immune-cell populations, sex-hormone effects, and ICI or TKI treatment rules. A genetic algorithm evolves synthetic tumor-cell genotypes, while Optuna tunes model parameters against overall-survival and survival-status outcomes from selected ARON registry cases.",
    "model_type": "Agent Based",
    "model_type_raw": "AGENT_BASED",
    "model_format": "Custom imperative Python/Mesa source (not SBML or CellML); Jupyter Notebook (IPYNB); CSV patient input",
    "model_software": "Python 3.13; Mesa 3.2.0; Optuna; Solara 1.48.0; pythreejs 2.4.2",
    "base_model": "OncoAgent RCC obesity-paradox agent-based learning model (PMID:33996779)",
    "model_id": "GitHub:marco-caputo/RCC-agent-learning-model@40220d6c398d90b41971f102acb9f84838982601",
    "repository_url": "https://github.com/marco-caputo/RCC-agent-learning-model/tree/40220d6c398d90b41971f102acb9f84838982601",
    "repository_host": "GitHub",
    "publication": "PMID:42064045",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Renal Cell Carcinoma",
    "disease_id": "MONDO:0005086",
    "category": "Cancer",
    "parents": [
      "Kidney Cancer"
    ],
    "variables": [
      "Patient sex",
      "Treatment regimen",
      "Treatment start",
      "Tumor-cell count",
      "Simulated overall survival",
      "Mean tumor mutation mask"
    ],
    "variable_ids": [
      "sex",
      "treatment",
      "treatment_start",
      "Tumor Cells",
      "steps",
      "average_mutation_mask"
    ],
    "variable_terms": [],
    "num_variables": 6,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Renal Epithelial Malignancy"
    ],
    "num_mechanisms": 1,
    "findings": [
      "Female-model runs showed delayed initial responses followed by stronger late immune activation and rapid regression, whereas male-model runs showed steadier early responses but greater modeled tumor resilience.",
      "Parameter tuning used seven RCC records and 26 Optuna trials for each objective; the paper reports lower aggregate prediction MSE and increasingly stable CI, without held-out validation."
    ],
    "num_findings": 2,
    "evidence_refs": [
      "PMID:42064045"
    ],
    "num_evidence": 1,
    "notes": "The GitHub repository is pinned at unsigned commit 40220d6c398d90b41971f102acb9f84838982601 (tree acfe9582f716869dc965aad04c11f279a5c13470) and has no tags or releases. Zenodo record 10.5281/zenodo.18727138 archives software version 1.0.0 as RCC-ALM.zip (SHA-256 4e7c38b570916555fac9fd422f0e5b8d52c5ebd2f8c93a708f3b0dedf4745358), although pyproject.toml calls the package 0.1.0; all 72 archived files are byte-identical to the pinned Git tree. Software Heritage directory swh:1:dir:570c82c75e1f417940762d4d66706f3467df706c contains the matching inner Git-tree directory, but no revision object for the commit resolves, so it preserves deposited content rather than Git history. The repository LICENSE and Zenodo software record are MIT. The upstream ARON-1 dataset is Zenodo DOI 10.5281/zenodo.13353313 under CC BY 4.0. The repository contains three byte-identical copies of a derived seven-row, 19-column CSV (SHA-256 aef040b2d21069fcdb58aca45a3331fa03c85c2dfadf6b9d5e8bc713cbf1d585), but does not cite that DOI, state data-specific attribution or licensing, or provide the manual selection and conversion procedure. Curator smoke testing installed the requirements under Python 3.13.9, constructed and advanced the 643-agent default model, exercised a small data pipeline, and completed the documented 100-step non-GUI command. That command emits only console traces and does not reproduce a paper result. Reproducibility remains partial: dependencies are not fully pinned or locked; the documented Solara interface fails with the resolved unbounded Starlette version; the built wheel omits required package data and uses incompatible src.* imports outside the checkout; and the analysis notebook has no executed outputs or reference results. There are 83 tuned weights for seven non-held-out cases. The MSE result-loading code mistakenly reloads CI parameters, repeat-count handling is defective, stochastic antigen selection depends on Python hash ordering, and a class-global tumor blood-source list can contaminate repeated runs. The model is exploratory and hypothesis-generating, not a clinically validated patient digital twin. Generic mutation adaptation does not justify linking it to the entry's histologic-and-molecular-subtype node, and it does not encode the PRR15/NF-\u03baB/FDX1 cuproptosis mechanism.",
    "creation_date": "2026-02-02T00:16:36Z",
    "page_url": "../../pages/disorders/Renal_Cell_Carcinoma.html#computational-model-rcc-3d-agent-based-learning-model",
    "source_file": "kb/disorders/Renal_Cell_Carcinoma.yaml"
  },
  {
    "model_key": "Phenylketonuria--computational-model-recon3d-with-pah-knockout--1",
    "name": "Recon3D with PAH knockout",
    "description": "Human genome-scale metabolic model simulating phenylalanine hydroxylase deficiency",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "SBML",
    "model_software": "COBRApy",
    "base_model": "Recon3D",
    "model_id": "Recon3D",
    "repository_url": "https://github.com/VirtualMetabolicHuman/Recon",
    "repository_host": "GitHub",
    "publication": "PMID:29457794",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Phenylketonuria",
    "disease_id": "MONDO:0009861",
    "category": "Genetic",
    "parents": [
      "Metabolic Disease",
      "Inborn Error of Metabolism"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [
      "PAH"
    ],
    "perturbation_ids": [
      "hgnc:8582"
    ],
    "modeled_mechanisms": [
      "Hepatic PAH Enzyme Deficiency",
      "Hyperphenylalaninemia"
    ],
    "num_mechanisms": 2,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [
      "PMID:29457794"
    ],
    "num_evidence": 1,
    "notes": "",
    "creation_date": "2025-12-19T14:27:56Z",
    "page_url": "../../pages/disorders/Phenylketonuria.html#computational-model-recon3d-with-pah-knockout",
    "source_file": "kb/disorders/Phenylketonuria.yaml"
  },
  {
    "model_key": "Fanconi_Anemia--computational-model-repair-fanc-high-content-screening-platform--5",
    "name": "REPAIR-FANC High Content Screening Platform",
    "description": "Cell-based high content screening platform using TALEN-mediated FANCA-deficient U2OS cells stably expressing YFP-FANCD2 to monitor FA/BRCA pathway activity via fluorescent FANCD2 foci formation. Screened 3802 compounds including 1200 FDA-approved drugs for potential FA pathway rescue.",
    "model_type": "Unclassified",
    "model_type_raw": "",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "",
    "repository_url": "",
    "repository_host": "No repository link",
    "publication": "PMID:32605631",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Fanconi_Anemia",
    "disease_id": "MONDO:0019391",
    "category": "Genetic",
    "parents": [
      "Bone Marrow Failure",
      "Congenital Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [
      "None of the 3802 compounds tested were able to rescue FANCA-dependent FANCD2 foci formation",
      "Platform demonstrates feasibility for high-throughput screening in FA therapeutics",
      "Some compounds showed mild reduction in chromosomal instability markers"
    ],
    "num_findings": 3,
    "evidence_refs": [
      "PMID:32605631"
    ],
    "num_evidence": 1,
    "notes": "",
    "creation_date": "2025-12-04T16:57:31Z",
    "page_url": "../../pages/disorders/Fanconi_Anemia.html#computational-model-repair-fanc-high-content-screening-platform",
    "source_file": "kb/disorders/Fanconi_Anemia.yaml"
  },
  {
    "model_key": "Type_2_Diabetes_Mellitus--computational-model-topp-beta-cell-mass-insulin-glucose-model--0",
    "name": "Topp Beta-Cell Mass / Insulin / Glucose Model",
    "description": "Minimal three-ODE dynamical model of the glucose regulatory system (Topp et al. 2000): plasma glucose, plasma insulin, and beta-cell mass, with fast glucose/insulin dynamics on a slow beta-cell-mass manifold. For normal parameters the system is bistable - a physiological steady state (euglycemia) and a pathological, insulinopenic steady state (beta-cell-mass collapse and severe hyperglycemia) separated by a saddle. This makes it the reference dynamical substrate for type 2 diabetes: reduced insulin sensitivity, impaired secretion, or hepatic glucose overproduction decompensates the at-risk state to overt diabetes, and it is wired for perturbation analysis (see the model config sidecar) so that both risk genes and glucose-lowering treatments can be simulated as parameter changes.",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "SBML",
    "model_software": "COPASI",
    "base_model": "",
    "model_id": "BIOMD0000000341",
    "repository_url": "https://www.ebi.ac.uk/biomodels/BIOMD0000000341",
    "repository_host": "BioModels",
    "publication": "PMID:11013117",
    "runnable": "Runnable in-repo",
    "source_type": "Disorder",
    "source_name": "Type 2 Diabetes Mellitus",
    "disease_id": "MONDO:0005148",
    "category": "Complex",
    "parents": [
      "Diabetes Mellitus",
      "Metabolic Disease",
      "Endocrine Disease"
    ],
    "variables": [
      "Fasting_Plasma_Glucose",
      "Plasma_Insulin",
      "Beta_Cell_Mass"
    ],
    "variable_ids": [
      "G",
      "I",
      "B"
    ],
    "variable_terms": [
      "Hyperglycemia",
      "Hyperinsulinemia",
      "glucose"
    ],
    "num_variables": 3,
    "perturbations": [
      "PPARG",
      "TCF7L2",
      "KCNJ11",
      "HNF1A",
      "GCK",
      "SLC5A2"
    ],
    "perturbation_ids": [
      "hgnc:9236",
      "hgnc:11641",
      "hgnc:6257",
      "hgnc:11621",
      "hgnc:4195",
      "hgnc:11037"
    ],
    "modeled_mechanisms": [
      "Insulin Resistance",
      "Beta Cell Dysfunction",
      "Hepatic Glucose Overproduction"
    ],
    "num_mechanisms": 3,
    "findings": [
      "For normal parameters the model is bistable, with a physiological (euglycemic) and a pathological (hyperglycemic, beta-cell-collapse) steady state separated by a saddle - the dynamical basis for decompensation to overt diabetes.",
      "The model defines three routes to prolonged hyperglycemia (regulated hyperglycemia, saddle-node bifurcation, and dynamical hyperglycemia), mapping onto insulin-resistance, secretory-failure, and hepatic-output drivers of type 2 diabetes."
    ],
    "num_findings": 2,
    "evidence_refs": [
      "PMID:11013117"
    ],
    "num_evidence": 1,
    "notes": "Wired for dismech-perturb (models/BIOMD0000000341.config.yaml). The disease-severity dial is insulin sensitivity si (baseline_gfr 0.72 = healthy); the deposited initial state (G=250 mg/dL) sits on the model's unstable saddle, i.e. the metabolically at-risk / impaired-fasting tipping point. Glucose-lowering treatments are simulated as parameter changes: metformin (R0 down), thiazolidinedione (si up), SGLT2 inhibitor (Eg0 up, insulin-independent), sulfonylurea/GLP-1 (sigma up), insulin therapy (net insulin action up). Insulin-independent therapies (SGLT2 inhibition, metformin) and sensitizers (TZD) recompensate the model to euglycemia, whereas a pure secretagogue fails once beta-cell mass has collapsed - reproducing secondary secretagogue failure in advanced disease. Thresholds are calibrated to model steady-state values, not clinical reference ranges.",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Type_2_Diabetes_Mellitus.html#computational-model-topp-beta-cell-mass-insulin-glucose-model",
    "source_file": "kb/disorders/Type_2_Diabetes_Mellitus.yaml"
  },
  {
    "model_key": "Familial_Long_QT_Syndrome--computational-model-tor-ord-human-ventricular-myocyte-model--2",
    "name": "ToR-ORd Human Ventricular Myocyte Model",
    "description": "Tomek-Rodriguez-O'Hara-Rudy refinement of the ORd model, recalibrated and independently validated across health, disease, and drug block, with a reformulated L-type Ca2+ current and a replaced hERG (I_Kr) current. It scales from single-cell ionic dynamics to whole-organ simulation including the electrocardiogram, and is a current reference human ventricular model for LQTS repolarization and drug-block studies.",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "CellML",
    "model_software": "Software not recorded",
    "base_model": "O'Hara-Rudy ORd human ventricular action potential model (PMID:21637795)",
    "model_id": "",
    "repository_url": "https://github.com/jtmff/torord",
    "repository_host": "GitHub",
    "publication": "PMID:31868580",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Familial Long QT Syndrome",
    "disease_id": "MONDO:0019171",
    "category": "Genetic",
    "parents": [
      "Cardiac Arrhythmia",
      "Channelopathy"
    ],
    "variables": [
      "Membrane potential",
      "Action potential duration at 90% repolarization (APD90)"
    ],
    "variable_ids": [
      "v",
      "APD90"
    ],
    "variable_terms": [
      "Prolonged QTc interval"
    ],
    "num_variables": 2,
    "perturbations": [
      "KCNH2"
    ],
    "perturbation_ids": [
      "hgnc:6251"
    ],
    "modeled_mechanisms": [
      "Prolonged Ventricular Action Potential Duration"
    ],
    "num_mechanisms": 1,
    "findings": [
      "ToR-ORd is validated under healthy and key disease conditions and under drug blockade, supporting its use for LQTS and drug-induced repolarization studies"
    ],
    "num_findings": 1,
    "evidence_refs": [
      "PMID:31868580"
    ],
    "num_evidence": 1,
    "notes": "Code (MATLAB and CellML), the validation pipeline, and human AP morphology data at github.com/jtmff/torord; a CellML exposure is also in the Physiome Model Repository.",
    "creation_date": "2026-04-14T05:37:14Z",
    "page_url": "../../pages/disorders/Familial_Long_QT_Syndrome.html#computational-model-tor-ord-human-ventricular-myocyte-model",
    "source_file": "kb/disorders/Long_QT_Syndrome.yaml"
  },
  {
    "model_key": "Parkinson's_Disease--computational-model-whole-dopaminergic-neuron-sbml-model--1",
    "name": "Whole Dopaminergic Neuron SBML Model",
    "description": "Large-scale Systems Biology Markup Language (SBML) model of dopaminergic neuron containing 139 reactions and 111 metabolites. Captures dopamine synthesis, vesicular storage, release, reuptake, and degradation alongside mitochondrial function and oxidative stress.\n",
    "model_type": "Kinetic",
    "model_type_raw": "KINETIC",
    "model_format": "SBML",
    "model_software": "Software not recorded",
    "base_model": "",
    "model_id": "MODEL1302200000",
    "repository_url": "https://www.ebi.ac.uk/biomodels/MODEL1302200000",
    "repository_host": "BioModels",
    "publication": "PMID:24196439",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Parkinson's Disease",
    "disease_id": "MONDO:0005180",
    "category": "Complex",
    "parents": [
      "Neurodegenerative Disease",
      "Movement Disorder"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [
      "Striatal Dopamine Deficiency",
      "Mitochondrial Dysfunction"
    ],
    "num_mechanisms": 2,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Enables simulation of drug effects on dopaminergic neurotransmission",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Parkinson's_Disease.html#computational-model-whole-dopaminergic-neuron-sbml-model",
    "source_file": "kb/disorders/Parkinsons_Disease.yaml"
  },
  {
    "model_key": "Diabetes_mellitus--computational-model-whole-body-human-metabolic-model-for-diabetes--1",
    "name": "Whole-Body Human Metabolic Model for Diabetes",
    "description": "Multi-organ metabolic model (Harvey/Harvetta) capturing inter-organ metabolic fluxes in diabetes. Models liver, muscle, adipose, and pancreas metabolism with tissue-specific constraints derived from omics data.",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "Recon3D",
    "model_id": "",
    "repository_url": "https://www.vmh.life/",
    "repository_host": "Virtual Metabolic Human",
    "publication": "PMID:32463598",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Diabetes mellitus",
    "disease_id": "MONDO:0005015",
    "category": "Complex",
    "parents": [
      "endocrine pancreas disorder",
      "glucose metabolism disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [
      "PMID:32463598"
    ],
    "num_evidence": 1,
    "notes": "Predicts diabetes biomarkers and drug effects across multiple organs",
    "creation_date": "2026-02-21T15:39:12Z",
    "page_url": "../../pages/disorders/Diabetes_mellitus.html#computational-model-whole-body-human-metabolic-model-for-diabetes",
    "source_file": "kb/disorders/Diabetes_Mellitus.yaml"
  },
  {
    "model_key": "Type_2_Diabetes_Mellitus--computational-model-whole-body-human-metabolic-model-for-diabetes--2",
    "name": "Whole-Body Human Metabolic Model for Diabetes",
    "description": "Multi-organ metabolic model (Harvey/Harvetta) capturing inter-organ metabolic fluxes in diabetes. Models liver, muscle, adipose, and pancreas metabolism with tissue-specific constraints derived from omics data.\n",
    "model_type": "Genome Scale Metabolic",
    "model_type_raw": "GENOME_SCALE_METABOLIC",
    "model_format": "Format not recorded",
    "model_software": "Software not recorded",
    "base_model": "Recon3D",
    "model_id": "",
    "repository_url": "https://www.vmh.life/",
    "repository_host": "Virtual Metabolic Human",
    "publication": "PMID:32472720",
    "runnable": "Reference only",
    "source_type": "Disorder",
    "source_name": "Type 2 Diabetes Mellitus",
    "disease_id": "MONDO:0005148",
    "category": "Complex",
    "parents": [
      "Diabetes Mellitus",
      "Metabolic Disease",
      "Endocrine Disease"
    ],
    "variables": [],
    "variable_ids": [],
    "variable_terms": [],
    "num_variables": 0,
    "perturbations": [],
    "perturbation_ids": [],
    "modeled_mechanisms": [],
    "num_mechanisms": 0,
    "findings": [],
    "num_findings": 0,
    "evidence_refs": [],
    "num_evidence": 0,
    "notes": "Predicts diabetes biomarkers and drug effects across multiple organs",
    "creation_date": "2025-12-18T17:01:35Z",
    "page_url": "../../pages/disorders/Type_2_Diabetes_Mellitus.html#computational-model-whole-body-human-metabolic-model-for-diabetes",
    "source_file": "kb/disorders/Type_2_Diabetes_Mellitus.yaml"
  }
];
window.searchMetrics = {
  "total_models": 46,
  "total_source_entries": 19,
  "total_model_types": 7,
  "total_runnable": 4,
  "total_with_repository": 21
};
window.dispatchEvent(new Event('searchDataReady'));
